### ISSUE TITLE
( JIRA #5 ) No Branding on email receipt pdf

### ISSUE THREAD

**Issue by leobardoramon** [gosha1128/NYUAMS#408]
The email receipt that is sent to user does not have any [NYU] branding. see attachment for email sent.
![ams-email-receipt](https://cloud.githubusercontent.com/assets/2165796/5500516/1abcf3ec-8703-11e4-9dbd-12c43e2780a5.jpg)

**Comment by NYU-AMS** [comment]
this is low on the list. We change it when we update our name.

put on hold for now
