### ISSUE TITLE
( JIRA #11 ) Projects > Duplicates Allowed

### ISSUE THREAD

**Issue by leobardoramon** [gosha1128/NYUAMS#414]
Projects > Duplicate Project Allowed

User is able to create multiple project with the exact same name, attributes and Client. The system is not recognizing this as a duplicate.
see attachemtn
![projects-dupsaccepted](https://cloud.githubusercontent.com/assets/2165796/5500551/d2b178ba-8703-11e4-96ae-d6710ec91077.jpg)

**Comment by NYU-AMS** [comment]
this is not a problem.   we have clients that will resubmit the same project

**Comment by NYU-AMS** [comment]
Close

**Comment by leobardoramon** [comment]
"Known Issue"
