### ISSUE TITLE
( JIRA #12 ) Projects > New Project > New Client > No field validation is being performed

### ISSUE THREAD

**Issue by leobardoramon** [gosha1128/NYUAMS#415]
Projects > New Project > New Client > No field validation is being performed

Application does not seem to perform any field level validation allowing special characters to be entered for phone numbers and even allowing an email to be that starts with "@" or even have multiple "@" in it.
See attachment for UI detail.
![projects-nofieldvalidations](https://cloud.githubusercontent.com/assets/2165796/5500555/ea199398-8703-11e4-8a89-9e50d163982f.jpg)

**Comment by leobardoramon** [comment]
Email field is fixed.

Andrew,

What format should we use for Phone?  We're wondering about extensions (also, within the university).

**Comment by NYU-AMS** [comment]
we should use this format 
212-998-3610 
Can we add a extension field the is not required to be filled in.

**Comment by leobardoramon** [comment]
Andrew, can we make the "Alt Phone" field --> "Ext. / Alt. Phone" field?

**Comment by NYU-AMS** [comment]
Yes

Sent from my iPhone

On Apr 8, 2015, at 10:58 PM, leobardoramon <notifications@github.com> wrote:

Andrew, can we make the "Alt Phone" field --> "Ext. / Alt. Phone" field?

—
Reply to this email directly or view it on GitHub
<https://github.com/gosha1128/NYUAMS/issues/415#issuecomment-91101725>.
