### ISSUE TITLE
( JIRA #14 ) Clients > New Client > Client Information > Net ID required even though Skip LDAP is checked

### ISSUE THREAD

**Issue by leobardoramon** [gosha1128/NYUAMS#417]
Clients > New Client > Client Information > Net ID required even though Skip LDAP is checked

User is creating a new Client and choses to check the "Skip" option for Locate Client in LDAP. Even though this option is checked the application is still requiring that you enter a NetID for the client
![client-netid-check](https://cloud.githubusercontent.com/assets/2165796/5500562/17207096-8704-11e4-974f-98daa7b4c3d1.jpg)

**Comment by NYU-AMS** [comment]
keep the NetID required.

-Andrew

Close

**Comment by leobardoramon** [comment]
The AMS needs the option of entering their own net id, so with this situation they can enter a "custom" net id
