### ISSUE TITLE
Cannot reach qaamsdb1 server

### ISSUE THREAD

**Issue by gosha1128** [gosha1128/NYUAMS#424]
OK, finally installed EBS application on qaamsdb1 and the app is running.

It seems we can't reach the web application at the url as follows ( as we can on DEV and the PROD instances. )

qaamsdb1.home.nyu.edu/js/login.html

Could someone verify the DNS name ?  Also, is the firewall setup to allow port 80 and 443 traffic ?

Thanks !

**Comment by leobardoramon** [comment]
Closing now
