### ISSUE TITLE
Test Case: Admin>emails - No net ID for system-generated emails

### ISSUE THREAD

**Issue by leobardoramon** [gosha1128/NYUAMS#457]
Since Metrics reports and digests are considered system-generated, no net ID is recorded.

Should something be entered here?
![screen shot 2015-04-14 at 11 40 26 pm](https://cloud.githubusercontent.com/assets/2165796/7182446/5bffaed4-e41f-11e4-8dc1-048ee89092a9.png)

**Comment by NYU-AMS** [comment]
I think is should just be removed.

-Andrew

**Comment by leobardoramon** [comment]
Closing
