### ISSUE TITLE
Test Case: Orders>part(s)>Part Status update - Awaiting Client & Test Complete are the same

### ISSUE THREAD

**Issue by leobardoramon** [gosha1128/NYUAMS#510]
Can we condense these?
![screen shot 2015-06-16 at 4 55 23 pm](https://cloud.githubusercontent.com/assets/2165796/8194301/d0c603fe-1448-11e5-8a7a-c6b27ef37023.png)

**Comment by gosha1128** [comment]
are you sure ? low effort

**Comment by leobardoramon** [comment]
No.  Closing Issue
