### ISSUE TITLE
Test Case:  ( sjs ) Projects>consultation(s) - Enhancement, Appointments

### ISSUE THREAD

**Issue by leobardoramon** [gosha1128/NYUAMS#539]
The AMS would like to be able to create session appointments for a future day.

This may require some type of "confirm" v. "decline" option, or a notification/reminder and email scheduler to client.  Once the appointment has been confirmed, the time is deducted from the project's consultation time.

**Comment by gosha1128** [comment]
medium effort, need user interfac

**Comment by leobardoramon** [comment]
Closing Issue.  Will recreate if needed
