### ISSUE TITLE
Test Case: Orders>New Order Wiz (WF)> Pricing 

### ISSUE THREAD

**Issue by leobardoramon** [gosha1128/NYUAMS#548]
Pricing does not change appropriately when dimensions are switched using "Swap" checkbox in WF New Order Wiz.

Andrew will send updated pricing formula with completed logic.

**Comment by NYU-AMS** [comment]
heroes the fix

-Andrew
> On Aug 31, 2015, at 3:41 PM, leobardoramon <notifications@github.com> wrote:
> 
> Pricing does not change appropriately when dimensions are switched using "Swap" checkbox in WF New Order Wiz.
> 
> Andrew will send updated pricing formula with completed logic.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/gosha1128/NYUAMS/issues/548>.
> 

var c; //cost

//********** tier cost AKA Paper cost  Change able in the admin **********
var T1a = 47; // tier cost
var T2a = 57; // tier cost
var T3a = 63; // tier cost
var T1b = 34; // tier cost
var T2b = 41; // tier cost
var T3b = 45; // tier cost

//**************************** Change ******************************
var x = 42; // enter 42 or 58
var t = 1; // Tier number 
var l = 24; // the long side of the prvar
var s = 42; // the short side of the prvar
//**************************** Change ******************************



function wide_price_func() {
  if (x == 58) {

    if (t == 1) {
      if (s > l) { 
        c = (l / 12) * T1a;
      } else { 
        c = (s / 12) * T1a;
      }
    }
    if (t == 2) {
      if (s > l) { 
        c = (l / 12) * T2a;
      } else { 
        c = (s / 12) * T2a;
      }
    }
    if (t == 3) {
      if (s > l) { 
        c = (l / 12) * T3a;
      } else { 
        c = (s / 12) * T3a;
      }
    }
  }

  if (x == 42) {

    if (t == 1) {
      if (s > l) { 
        c = (l / 12) * T1b;
      } else { 
        c = (s / 12) * T1b;
      }
    }
    if (t == 2) {
      if (s > l) { 
        c = (l / 12) * T2b;
      } else { 
        c = (s / 12) * T2b;
      }
    }
    if (t == 3) {
      if (s > l) { 
        c = (l / 12) * T3b;
      } else { 
        c = (s / 12) * T3b;
      }
    }
  }

  console.log(c);  //prvar cost
}

**Comment by NYU-AMS** [comment]
Hey guys this is the really fix.   var 1 had to be updated to var L sorry for two txt files




> On Aug 31, 2015, at 3:59 PM, Andrew Buckland <andrew.buckland@nyu.edu> wrote:
> 
> heroes the fix
> 
> -Andrew
>> On Aug 31, 2015, at 3:41 PM, leobardoramon <notifications@github.com <mailto:notifications@github.com>> wrote:
>> 
>> Pricing does not change appropriately when dimensions are switched using "Swap" checkbox in WF New Order Wiz.
>> 
>> Andrew will send updated pricing formula with completed logic.
>> 
>> —
>> Reply to this email directly or view it on GitHub <https://github.com/gosha1128/NYUAMS/issues/548>.
>> 
> <Wide_fix.txt>


var c; //cost

//********** tier cost AKA Paper cost  Change able in the admin **********
var T1a = 47; // tier cost
var T2a = 57; // tier cost
var T3a = 63; // tier cost
var T1b = 34; // tier cost
var T2b = 41; // tier cost
var T3b = 45; // tier cost

//**************************** Change ******************************
var x = 42; // enter 42 or 58
var t = 1; // Tier number 
var L = 24; // the long side of the prvar
var s = 42; // the short side of the prvar
//**************************** Change ******************************



function wide_price_func() {
 if (x == 42) {
    if (t == 1) {
      if (L > x) {
        c = (L / 12) * T1b;
      } else { 
        c = (s / 12) * T1b;
      }
    }
        if (t == 2) {
      if (L > x)  {
        c = (L / 12) * T2b;
      } else { 
        c = (s / 12) * T2b;
      }
    }
        if (t == 3) {
      if (L > x)  {
        c = (L / 12) * T3b;
      } else { 
        c = (s / 12) * T3b;
      }
    }
  } 
  

  //**************************** 58 ******************************
    if (x == 58) {
    if (t == 1) {
      if (L > x) {
        c = (L / 12) * T1a;
      } else { 
        c = (s / 12) * T1a;
      }
    }
        if (t == 2) {
      if (L > x) {
        c = (L / 12) * T2a;
      } else { 
        c = (s / 12) * T2a;
      }
    }
        if (t == 3) {
      if (L > x) {
        c = (L / 12) * T3a;
      } else { 
        c = (s / 12) * T3a;
      }
    }
  }
  console.log(c);  //prvar cost
}

**Comment by NYU-AMS** [comment]
this is it 
> On Sep 1, 2015, at 11:32 AM, Andrew Buckland <andrew.buckland@nyu.edu> wrote:
> 
> Hey guys this is the really fix.   var 1 had to be updated to var L sorry for two txt files
> 
> 
> <fix.txt>
> 
>> On Aug 31, 2015, at 3:59 PM, Andrew Buckland <andrew.buckland@nyu.edu <mailto:andrew.buckland@nyu.edu>> wrote:
>> 
>> heroes the fix
>> 
>> -Andrew
>>> On Aug 31, 2015, at 3:41 PM, leobardoramon <notifications@github.com <mailto:notifications@github.com>> wrote:
>>> 
>>> Pricing does not change appropriately when dimensions are switched using "Swap" checkbox in WF New Order Wiz.
>>> 
>>> Andrew will send updated pricing formula with completed logic.
>>> 
>>> —
>>> Reply to this email directly or view it on GitHub <https://github.com/gosha1128/NYUAMS/issues/548>.
>>> 
>> <Wide_fix.txt>
> 


var c; //cost

//********** tier cost AKA Paper cost  Change able in the admin **********
var T1a = 47; // tier cost
var T2a = 57; // tier cost
var T3a = 63; // tier cost
var T1b = 34; // tier cost
var T2b = 41; // tier cost
var T3b = 45; // tier cost

//**************************** Change ******************************
var x = 42; // enter 42 or 58
var t = 1; // Tier number 
var L = 24; // the long side of the prvar
var s = 42; // the short side of the prvar
//**************************** Change ******************************



function wide_price_func() {
 if (x == 42) {
    if (t == 1) {
      if (L > x) {
        c = (L / 12) * T1b;
      } else { 
        c = (s / 12) * T1b;
      }
    }
        if (t == 2) {
      if (L > x)  {
        c = (L / 12) * T2b;
      } else { 
        c = (s / 12) * T2b;
      }
    }
        if (t == 3) {
      if (L > x)  {
        c = (L / 12) * T3b;
      } else { 
        c = (s / 12) * T3b;
      }
    }
  } 
  

  //**************************** 58 ******************************
    if (x == 58) {
    if (t == 1) {
      if (L > x) {
        c = (L / 12) * T1a;
      } else { 
        c = (s / 12) * T1a;
      }
    }
        if (t == 2) {
      if (L > x) {
        c = (L / 12) * T2a;
      } else { 
        c = (s / 12) * T2a;
      }
    }
        if (t == 3) {
      if (L > x) {
        c = (L / 12) * T3a;
      } else { 
        c = (s / 12) * T3a;
      }
    }
  }
  console.log(c);  //prvar cost
}

**Comment by gosha1128** [comment]
You guys can test this if you like....choose an ebs instance, cd
/opt/nyuams/node, git pull...locate the file under ebs dir and replace with
new one...test against this instance only ...add, commit, push via git...

**Comment by leobardoramon** [comment]
don't know how to replace the file in terminal, tried to edit the file in emacs and that didn't work.

Here's the log for the Terminal session:
https://docs.google.com/document/d/1WPStMgjP4_EOh-59-622ru3fBtBNFhmtHVjU5vDdHyI/edit

**Comment by gosha1128** [comment]
1.  you need to figure out how to upload the file to that machine using
rsync

2.  locate the original file under node/ebs somewhere

3.  copy over the new file into the old file's place

4.  then test

**Comment by leobardoramon** [comment]
This has been fixed.  Closing now
