### ISSUE TITLE
Test Case:  Admin/wide - issue with pricing for Device A / Cost Tier A

### ISSUE THREAD

**Issue by leobardoramon** [gosha1128/NYUAMS#553]
server:  http://54.209.192.94/
login:  leo
pw:  l6shooter

In Admin/wide, when changing price of Cost Tier A to $1, part calculator quotes a price of $4.83
  -this should be $1
  -not sure where this number is being pulled from
  -this does not happen with Cost Tier B when changing cost to $1

Andrew thinks that the code that mysql is using to figure the price is using old, incorrect formula
  -where can we find this code in mysql?

Temporary fix:  Divide desired cost by 4.83 to have a roughly accurate price.
![screen shot 2015-12-11 at 3 08 07 pm](https://cloud.githubusercontent.com/assets/2165796/11754546/0893f63a-a01a-11e5-9f71-82a0300acdf8.png)
![screen shot 2015-12-11 at 3 08 46 pm](https://cloud.githubusercontent.com/assets/2165796/11754545/0891b15e-a01a-11e5-9f06-c3ce2815a554.png)

**Comment by gosha1128** [comment]
OK, how's how you view what is in sql.

Note - this is a dangerous operation - so if you plan to modify anything
within SQL, make sure you have a recent backup.

At a command prompt, log into the RDS SQL instance:

For example ( use the RDS address for the SQL database you want to check )

>> mysql -h ebs.cdsq90t3hkch.us-east-1.rds.amazonaws.com -u ebs -p

At the SQL command prompt, do the following commands to list out the
relevant information:

mysql> show databases;

+--------------------+

| Database           |

+--------------------+

| information_schema |

| ebs                |

| innodb             |

| mysql              |

| performance_schema |

| test               |

| tmp                |

+--------------------+

7 rows in set (0.00 sec)


mysql> use ebs;

Reading table information for completion of table and column names

You can turn off this feature to get a quicker startup with -A


Database changed

mysql> show tables;

+---------------------------+

| Tables_in_ebs             |

+---------------------------+

| Accounts                  |

| Checks                    |

| Clients                   |

| Colors                    |

| Conpackages               |

| Consessions               |

| Devices                   |

| Digests                   |

| Emails                    |

| Files                     |

| Globals                   |

| Invoices                  |

| LaserMaterials            |

| Milestones                |

| Notes                     |

| Orders                    |

| PaperTypes                |

| Parts                     |

| Projects                  |

| RapidMaterials            |

| Receipts                  |

| Reports                   |

| Schedules                 |

| Templates                 |

| Tests                     |

| Transactions              |

| join_files_orders         |

| join_files_parts          |

| join_files_projects       |

| join_orders_notes         |

| join_projects_clients     |

| join_projects_conpackages |

| join_projects_notes       |

| join_projects_orders      |

| users                     |

+---------------------------+

35 rows in set (0.00 sec)


mysql> select * from PaperTypes;

+------+---------------------------------------+---------+------+------+------+---------+---------------------+---------------------+

| ptid | name                                  | dev     | tier | a    | b
  | pa      | createdAt           | updatedAt           |

+------+---------------------------------------+---------+------+------+------+---------+---------------------+---------------------+

|    1 | Epson Enhanced Matte 250 gsm          | Matthew |    1 | 0.34 |
0.45 | PA00001 | 2015-07-27 01:50:30 | 2015-12-01 17:40:36 |

|    2 | Epson Premium Luster 250 gsm          | Trixie  |    1 | 0.34 |
0.45 | PA00002 | 2015-07-27 01:50:30 | 2015-07-27 01:50:30 |

|    5 | Epson Somerset Velvet 255 gsm         | Matthew |    2 | 0.34 |
0.45 | PA00005 | 2015-07-27 01:50:30 | 2015-07-27 01:50:30 |

|    6 | Epson UltraSmooth Fine Art 250 gsm    | Matthew |    2 | 0.34 |
0.45 | PA00006 | 2015-07-27 01:50:30 | 2015-07-27 01:50:30 |

|    7 | Hahnemühle Photo Rag (matte) 308 gsm  | Matthew |    3 | 0.34 |
0.45 | PA00007 | 2015-07-27 01:50:30 | 2015-10-05 19:10:32 |

|    8 | Hahnemühle Fine Art Pearl 308 gsm     | Gonzo   |    3 | 0.34 |
0.45 | PA00008 | 2015-07-27 01:50:30 | 2015-07-27 01:50:30 |

|   12 | Epson Premium Satin Canvas            | Trixie  |    3 | 0.34 |
0.45 | PA00012 | 2015-07-27 01:50:30 | 2015-07-27 01:50:30 |

|   13 | Epson Premium Matte Canvas            | Trixie  |    3 | 0.34 |
0.45 | PA00013 | 2015-07-27 01:50:30 | 2015-07-27 01:50:30 |

|   14 | Crane Museo Max 250 gsm               | Matthew |    3 | 0.34 |
0.45 | PA00014 | 2015-07-27 01:50:30 | 2015-07-27 01:50:30 |

|   16 | Hahnemuehle Photo Rag Baryta          | NULL    |    3 | NULL |
NULL | NULL    | 2015-10-05 19:11:53 | 2015-10-05 19:11:53 |

|   17 | Hahnemuehle Photo Rag Satin           | NULL    |    3 | NULL |
NULL | NULL    | 2015-10-05 19:12:17 | 2015-10-05 19:12:17 |

|   18 | Innova FiBaRint Warm Cotton Gloss     | NULL    |    3 | NULL |
NULL | NULL    | 2015-10-05 19:12:55 | 2015-10-05 19:12:55 |

|   19 | Epson Premium Semimatte               | NULL    |    1 | NULL |
NULL | NULL    | 2015-11-05 16:11:00 | 2015-11-05 16:11:00 |

+------+---------------------------------------+---------+------+------+------+---------+---------------------+---------------------+

13 rows in set (0.01 sec)


mysql>

**Comment by leobardoramon** [comment]
Not experiencing issues anymore at this time...on HOLD for now
