### ISSUE TITLE
Test Case:  Scrolling issue

### ISSUE THREAD

**Issue by leobardoramon** [gosha1128/NYUAMS#554]
Not able to scroll all the way down

See Video: https://drive.google.com/open?id=0B_9JEK6SVk1bWEoyRHplVERLbVU

**Comment by gosha1128** [comment]
Can you give me a login so i can try it myself ?

-g

**Comment by leobardoramon** [comment]
IP:  http://52.0.50.223/js/login.html
login:  leo
pw:  l6shooter
domain:  Local

**Comment by leobardoramon** [comment]
this issue is directly related to #556 
Closing
