### ISSUE TITLE
Test Case:  Orders/New Order Wiz/panel1 - Go Button

### ISSUE THREAD

**Issue by leobardoramon** [gosha1128/NYUAMS#555]
IP:  http://52.0.50.223/js/login.html
login:  leo
pw:  l6shooter
domain:  Local

Existing function:
show projects by date of creation (ascending)
Desired function:
show projects by date of creation (DESCENDING)

See attachments for existing layout:
![1](https://cloud.githubusercontent.com/assets/2165796/12460583/67b63e8e-bf82-11e5-96b0-f3967be3e77d.png)
![2](https://cloud.githubusercontent.com/assets/2165796/12460580/67ab939e-bf82-11e5-8a55-f4677b0fbbfd.png)
![3](https://cloud.githubusercontent.com/assets/2165796/12460581/67ae51f6-bf82-11e5-8b5b-cf491ce1458b.png)
![4](https://cloud.githubusercontent.com/assets/2165796/12460582/67b115b2-bf82-11e5-998c-ebac8c125afa.png)

**Comment by gosha1128** [comment]
ok - can you please schedule some weekend time for this?  I think we can do
it pretty fast.

i'll need access to some kind of hosted dev environment where i can fix
code, you can test, we push the changes to production, etc, etc...

**Comment by leobardoramon** [comment]
I just scheduled that work session for this evening.  If you don't have
time, lmk and I'll change to tomorrow.

-Leo

**Comment by gosha1128** [comment]
That's fine...

**Comment by gosha1128** [comment]
3 is too early...it should be later like 6pm

**Comment by gosha1128** [comment]
If you can't make it just set me up with an ebs that I can play with...and
give me the details to ssh and web url and password...

**Comment by leobardoramon** [comment]
I'll send you info shortly, so that at 6pm you'll have enough time to ask
me for more urgent info, like roadblocks. I'll be availability for only an
hour at 6pm pst.

-Leo

**Comment by backprops** [comment]
OK fixed - test it here... http://54.209.192.94

**Comment by leobardoramon** [comment]
Looks good

![screen shot 2016-02-04 at 9 27 00 pm](https://cloud.githubusercontent.com/assets/2165796/12836588/64dc48fe-cb88-11e5-9920-55d1df287508.png)

![screen shot 2016-02-04 at 9 44 40 pm](https://cloud.githubusercontent.com/assets/2165796/12836610/8c2aa07c-cb88-11e5-8a9a-2caf088edb6f.png)
