### ISSUE TITLE
AWS:  New DEV Systems

### ISSUE THREAD

**Issue by leobardoramon** [gosha1128/NYUAMS#562]
ec2 instance "dev3"
IP:  http://54.164.124.142/

rds instance "dev1"
string:  dev1.cdsq90t3hkch.us-east-1.rds.amazonaws.com

**Comment by gosha1128** [comment]
Great !  So, i can get started with schema update work on these systems.

Please don't count on these dev systems to be up and running while I work
on them.  When I request testing then I will make sure they work...

George

**Comment by leobardoramon** [comment]
George,

as we design the new schema for the database...

-will this affect how new features and areas are implemented?
-should we work our designs around the new schema?
-what other things should we be considering?

**Comment by gosha1128** [comment]
No it won't change any visible features - it will just make a few things
faster

**Comment by gosha1128** [comment]
OK, so i did the most obvious optimizations and already there is a big win.  Please check out metrics now on DEV and let me know if it looks good.  If that level of performance is good enough for now, then let me know.  I can probably make it 10X - 20X faster, but that will take more time :)

**Comment by gosha1128** [comment]
The "easy" optimization I did should speed up other areas of the interface as well.  

I think you should go ahead and create a github issue for every area of the interface that you feel should go faster and prioritize.

**Comment by gosha1128** [comment]
Another thing...metrics works the way it does so that you always get the latest numbers when you go there.  We could also do something where we just "cache" the last computation of metrics so that when you go to metrics it shows the last status of metrics.  Maybe we put a button with lets you explicity recompute now.  This will be easy....let me know what you guys want.

**Comment by leobardoramon** [comment]
re: "easy" optimization
1.  In order to prepare for QA testing in the AWS, should I repeat steps for:
   (a)  creating QA rds instance and ec2 instance
   (b)  creating QA ec2 instance *only*
   (c)  wait for direction

2.  Does the "easy" optimization need testing at this point?

1. Yes to "refresh" button for metrics page.

See issue #556 for followup questions about Metrics issue

**Comment by gosha1128** [comment]
Right, so you need to quality testing as follows:

1) smoke test - a quick test of a small change to make sure something
hasn't horribly broken.  A smoke test should touch upon each major feature
in a light/quick way - you want a smoke test to be pretty fast.

2) deep test - this is a list of very specific tests and can take a while.
 usually you do this at the end of a release or before you deploy a change
to production.

3) DEV vs PRODUCTION testing - you usually do DEV testing when a major bug
or major feature has been created.  yes, you do this on an empty database
or a database with actual data.  After you've done DEV testing to your
satisfaction, then you deploy the new feature to production, and then do a
smoke test on that to make sure something screwy hasn't happened in the
update.   For the latter, you usually try to do this after-hours.

**Comment by gosha1128** [comment]
Hey, don't forget - the FILE SERVER machine should also be replicated for DEV.

You must use the same RDS + FILE SERVER backup combo, when bring up a DEV system to use past data !!

The DEV EC2 must be configured to use that DEV FILE SERVER.

**Comment by leobardoramon** [comment]
"devfiles" image has been created in AWS. Leo will Launch "devfiles" EC2 Instance today. Update to follow

**Comment by leobardoramon** [comment]
I'll be in-studio on Friday, I will launch "devfiles" AMI into live instance at that time.  Thank you

**Comment by leobardoramon** [comment]
I'm preparing to create "devfiles" instance now.

Q:  Should the instance "devfiles" point to the existing security group "launch-wizard-3" or should it have it's own unique copy of "launch-wizard-3" that has identical settings?

**Comment by gosha1128** [comment]
You should try to keep DEV and PROD systems separate as much as possible.

The firewall rules should be different - you don't want the systems to
accidentally talk to each other at all.

**Comment by leobardoramon** [comment]
Launching "devfiles" ec2 from "devfiles" AMI now

**Comment by leobardoramon** [comment]
not sure what parameters to put here:
![screen shot 2016-03-12 at 9 27 10 am](https://cloud.githubusercontent.com/assets/2165796/13723475/b8b7e78a-e834-11e5-8e3c-06a0e6e8ed26.png)

George?

**Comment by gosha1128** [comment]
Are you cloning an existing prod files ?

**Comment by leobardoramon** [comment]
Yes

**Comment by gosha1128** [comment]
Just keep whatever they recommend..it really should just be a clone...so
you should not need to change Nything

**Comment by gosha1128** [comment]
You'll have to change the /exports file on that machine...but you probably
new that

**Comment by leobardoramon** [comment]
"devfiles" instance is live.  I believe everything is pointing where it needs to.

I added the LGS ip ranges ( 50 - 65000 ) 
I added one IP range that PRODFILES started with and seemed important: 
   70.36.142.82(rw,insecure,no_subtree_check,sync,no_root_squash,no_all_squash)

Please advise.

![screen shot 2016-03-13 at 12 21 23 am](https://cloud.githubusercontent.com/assets/2165796/13727096/af21bcc2-e8b2-11e5-85b3-9cd22f3eebba.png)
![screen shot 2016-03-13 at 12 28 23 am](https://cloud.githubusercontent.com/assets/2165796/13727097/af331fa8-e8b2-11e5-959c-00a8024477b8.png)

Am I missing anything?

**Comment by gosha1128** [comment]
ok so you tested the DEV system end-to-end ?  it works right ?

**Comment by leobardoramon** [comment]
... Let me double check. Followup within two hours

**Comment by leobardoramon** [comment]
I'm trying to log into dev3 ( 54.164.124.142 ) and this is what I get:
<img width="574" alt="screen shot 2016-03-13 at 6 45 25 pm" src="https://cloud.githubusercontent.com/assets/2165796/13731933/df0210ec-e94b-11e5-99b4-fd4c849847e7.png">

**Comment by leobardoramon** [comment]
I am creating a new AMI using the ec2 instance PROD_GRANTS ( which is not in the load balancer ) which I will call dev4.  I'm not really sure why "dev3" isn't allowing me to log in, but let's try again.

**Comment by gosha1128** [comment]
if you end a bad password on purpose - what does it say ?

**Comment by leobardoramon** [comment]
( 54.165.224.16 ) "dev4" ec2 instance

  - (1) created , using instructions, https://docs.google.com/document/d/1pMeZZVu8yRwQlPnTnUYeHXCGC7XasfnAZZWYBamQEWs/edit

<img width="1882" alt="screen shot 2016-03-14 at 12 28 59 pm" src="https://cloud.githubusercontent.com/assets/2165796/13751405/605fb092-e9e0-11e5-91eb-2fd73d993eca.png">

  - (2) points to "dev1" rds instance via security group sg-e3833087

<img width="1605" alt="screen shot 2016-03-14 at 12 29 53 pm" src="https://cloud.githubusercontent.com/assets/2165796/13751421/7d395b5a-e9e0-11e5-9153-64e661dce305.png">

  - (3) started via Terminal using PROD1.pem key

<img width="912" alt="screen shot 2016-03-14 at 12 30 17 pm" src="https://cloud.githubusercontent.com/assets/2165796/13751436/8cc4085e-e9e0-11e5-8da4-c363561f8bbd.png">

  - (4a) points to devfiles via security group sg-6a43c012

<img width="1537" alt="screen shot 2016-03-14 at 12 31 32 pm" src="https://cloud.githubusercontent.com/assets/2165796/13751490/d7c32326-e9e0-11e5-826f-90a0717f742f.png">

    (4b) points to devfiles via /etc/exports via Terminal

<img width="1092" alt="screen shot 2016-03-14 at 12 33 51 pm" src="https://cloud.githubusercontent.com/assets/2165796/13751534/0bd1445e-e9e1-11e5-9956-42f1c002e6ad.png">


instance does not load when tested in browser

**Comment by leobardoramon** [comment]
server does not start in manual mode:
 "start app.js nfs"

<img width="1058" alt="screen shot 2016-03-14 at 12 54 25 pm" src="https://cloud.githubusercontent.com/assets/2165796/13752192/003d0026-e9e4-11e5-848c-b550854283b0.png">

**Comment by gosha1128** [comment]
no its:

>> sudo bash

>> node app.js nfs

it will print a bunch of stuff to screen - append that here

**Comment by leobardoramon** [comment]
<img width="1107" alt="screen shot 2016-03-14 at 1 03 30 pm" src="https://cloud.githubusercontent.com/assets/2165796/13752498/58412dd2-e9e5-11e5-9174-ca4edd29223f.png">

**Comment by leobardoramon** [comment]
-side note- I'm 90% sure that if I point "dev3" ( ec2 instance ) to "ebs" ( rds instance ) , it will then work.  Therefore, I believe the problem lies in the RDS instance "dev1" parameters...

**Comment by gosha1128** [comment]
Yes, so EBS can't connect to your RDS instance.

So

1) check the SQL connection string - that you are going to the RDS instance
you want

2) check the firewall settings between RDS instance and the EBS ( you have
to make sure RDS ports are open )

**Comment by leobardoramon** [comment]
how do I do "1)" ?

**Comment by gosha1128** [comment]
Thats in the file db/config.js.

You would take the RDS connection string thats shown in the amazon res
console, and put it into the config.js file at the right place.

This is how EBS knows the RDS address...

**Comment by leobardoramon** [comment]
do I (a) run any special commands after updating this doc or (b) just restart server as usual?

**Comment by gosha1128** [comment]
the procedure should be:

1) make necessary changes to db/config.js

2) test changes by starting server in manual mode - check server starts,
check you can access the ebs site

3) if #2 looks good, then restart server in forever mode - check you can
access the abs site again

4) you can log out of the ec2 instance

**Comment by leobardoramon** [comment]
success

<img width="1509" alt="screen shot 2016-03-14 at 1 23 41 pm" src="https://cloud.githubusercontent.com/assets/2165796/13753109/15b7bf28-e9e8-11e5-960a-ec9e600857e9.png">

server was restarted in forever mode and still works.

Thank you.

Smoke test results to follow

**Comment by gosha1128** [comment]
Yes, great.

You want some test which verifies you are talking the the DEV prod files -
this is super important.  If DEV starts writing to production prod files
then it will screw up PRODUCTION in bad ways.

-g

**Comment by leobardoramon** [comment]
smoketest tracking: 
IP:  http://54.165.224.16/

Test:  Projects>file(s) - Upload file
Status:  Failed

<img width="1418" alt="screen shot 2016-03-14 at 2 19 01 pm" src="https://cloud.githubusercontent.com/assets/2165796/13755119/0c9cd3a8-e9f0-11e5-98cd-31a06a66db50.png">

after failing to upload a file, I tried connecting to the devfiles server via Finder>Go>Connect to server...

This did not work.

I have not yet gone through the steps of:
  1. installing homebrew, etc
  2. ...
  3. setting up for fileproxy server

is this related to that portion of setup?

**Comment by gosha1128** [comment]
This means your physical machine could not connect to that files server
machine at that ip address.

You need to make sure:

1) the firewall rules are setup so that your physical machine can talk to
the files server machine

2) the exports file also needs to know about your physical machine

NOTE, if its a physical machine in the NYU lab, then you need to figure out
the right ip address or address range that amazon sees.  Maybe
"whatismyipaddress" or some other service will be useful here

**Comment by leobardoramon** [comment]
Okay

I've verified the following:

1. my actual IP address

<img width="676" alt="screen shot 2016-03-14 at 2 41 56 pm" src="https://cloud.githubusercontent.com/assets/2165796/13755737/fed7c87e-e9f2-11e5-8bf5-dde8652ac135.png">

2. devfiles security group is the one I'm working from

<img width="1883" alt="screen shot 2016-03-14 at 2 33 20 pm" src="https://cloud.githubusercontent.com/assets/2165796/13755639/89fb6aa6-e9f2-11e5-964f-a5c4ff6db6c4.png">

3. this IP range is in Security Group launch-wizard-13 ( not sure if the port range [ 50 - 65000 ] but the IP range is correct, as verified by Andrew )

<img width="1510" alt="screen shot 2016-03-14 at 2 33 52 pm" src="https://cloud.githubusercontent.com/assets/2165796/13755681/bf388320-e9f2-11e5-9eb4-18265f042f9d.png">

4. this IP range is in the /exports file in devfiles

<img width="1095" alt="screen shot 2016-03-14 at 2 34 46 pm" src="https://cloud.githubusercontent.com/assets/2165796/13755665/a7b0e01c-e9f2-11e5-976d-9a7511e9de01.png">

WHere should I go from here?

**Comment by leobardoramon** [comment]
Now I'm going to add the specific IP address for this machine and see what happens...

**Comment by leobardoramon** [comment]
Q:  Should I be using the SAME rules for IP ranges as I do for individual IPs in the etc/exports files?
  - (ro,insecure,no_subtree_check,sync)
  - if not, this might be part of the cause for LGS's "lockouts" #559

**Comment by gosha1128** [comment]
Not sure actually.  You might need to read up on exports file.

Because we don't know the problem, anything might be the problem :)

---

Also, bear in mind that the IP address you see on the physical machine, may
not be the ip address as seen by anyone outside of the NYU firewall (
including amazon servers. )

For this - you might need to use "whatismyipaddress.com"

-g

**Comment by leobardoramon** [comment]
* I just noticed that earlier I was trying to connect to the wrong IP address... *

After adding the specific IP address for this machine connection ( 172.22.69.42 ) to (1) AWS and (2) devfiles/etc/exports, I tried it with the correct IP address just now.  It did not work

<img width="1400" alt="screen shot 2016-03-14 at 3 03 50 pm" src="https://cloud.githubusercontent.com/assets/2165796/13756373/ffd168e0-e9f5-11e5-8e8f-d2e324d2c345.png">

I'll read up on exports files.

**Comment by leobardoramon** [comment]
Can you recommend a good starting point for reading up on this?

"exports file rules" is a bit too vague for google and I think it might be the wrong search parameter altogether.

**Comment by gosha1128** [comment]
Sounds like a firewall thing really.

What does "whatismyipaddress.com" say ?

-g

**Comment by gosha1128** [comment]
nfs exports file syntax

**Comment by leobardoramon** [comment]
You were right.

whatismyip.com
<img width="1466" alt="screen shot 2016-03-14 at 3 11 15 pm" src="https://cloud.githubusercontent.com/assets/2165796/13756830/25ae02e2-e9f8-11e5-82a4-f01facf29eb7.png">

added to aws and /etc/exports
<img width="1560" alt="screen shot 2016-03-14 at 3 14 11 pm" src="https://cloud.githubusercontent.com/assets/2165796/13756866/4bbca0c4-e9f8-11e5-91e0-148a52131ca8.png">
<img width="1089" alt="screen shot 2016-03-14 at 3 14 33 pm" src="https://cloud.githubusercontent.com/assets/2165796/13756865/4bbc4e4e-e9f8-11e5-8140-73f473dc4e03.png">

it connected
<img width="1699" alt="screen shot 2016-03-14 at 3 16 39 pm" src="https://cloud.githubusercontent.com/assets/2165796/13756879/59af80ac-e9f8-11e5-833a-4b35fd109203.png">

**Comment by leobardoramon** [comment]
the file still didn't upload, creating new GitHub issue now

**Comment by gosha1128** [comment]
Yes, so firewalls are tricky this way.  Internet traffic can get magically
transformed in unexpected places.  You might want to check with NYU if this
public ip address will change or if its always the same from machines in
the lab...I don't know who you would check with.

If the public ip changes with you knowing - that could be related to the
lock out issue.

I would escalate this....

**Comment by leobardoramon** [comment]
Andrew has been notified.  He will find more.

This is very good news.  Thank you

**Comment by leobardoramon** [comment]
Please add IP range to devfiles Inbound security rules, when setting up
![screen shot 2016-03-23 at 11 40 55 am](https://cloud.githubusercontent.com/assets/2165796/14006040/4dc9aa30-f126-11e5-8152-f7d73f6be9bd.png)

**Comment by leobardoramon** [comment]
See thread from issue #568 for date range 3/21 - 3/23, as it related to this issue.

Creating new snapshots for entire DEV environment now

**Comment by leobardoramon** [comment]
All snapshots have been created
![screen shot 2016-03-25 at 2 47 34 am](https://cloud.githubusercontent.com/assets/2165796/14042298/e5e7c6ac-f235-11e5-8c2d-cf9173b3136f.png)
![screen shot 2016-03-25 at 2 47 40 am](https://cloud.githubusercontent.com/assets/2165796/14042299/e5e86bc0-f235-11e5-9c1c-a4e6a09824b3.png)
![screen shot 2016-03-25 at 2 53 13 am](https://cloud.githubusercontent.com/assets/2165796/14042300/e5e9ee5a-f235-11e5-8710-4adb4a1df78d.png)

**Comment by leobardoramon** [comment]
After creating AMI of PROD3 server instance , PROD3 server is "Out Of Service"

![screen shot 2016-03-25 at 2 56 42 am](https://cloud.githubusercontent.com/assets/2165796/14042331/280353f8-f236-11e5-8d6d-c1fcee45ffc9.png)
![screen shot 2016-03-25 at 2 57 43 am](https://cloud.githubusercontent.com/assets/2165796/14042332/2811d888-f236-11e5-8d95-ca85f29478cc.png)

Please see Terminal output after PROD3 server was restarted using command <<node app.js nfs>>

![screen shot 2016-03-25 at 2 59 09 am](https://cloud.githubusercontent.com/assets/2165796/14042354/5484e388-f236-11e5-9892-271b473365ac.png)

**Comment by leobardoramon** [comment]
PROD is up and running

**Comment by gosha1128** [comment]
So you have an isolated DEV system ?

**Comment by leobardoramon** [comment]
Not yet, on its way

**Comment by gosha1128** [comment]
OK, when you do - just send me a prioritized list of bugs to fix.

We will have to practice fixing on the DEV system, testing, deploying to
PROD, testing, etc...

**Comment by leobardoramon** [comment]
George,

Does DEV need its own VPC?

**Comment by gosha1128** [comment]
Not needed... But a good idea

**Comment by leobardoramon** [comment]
DEV environment will be set up today

**Comment by leobardoramon** [comment]
Andrew doesn't think a new VPC is necessary for the DEV environment. We will move forward without creating a new VPC

**Comment by gosha1128** [comment]
Sounds good.  You could essentially do the same thing with the right set of
firewall rules...make sure PROD and DEV can't see each other anywhere !  :)

-g

**Comment by leobardoramon** [comment]
George,

I'm launching devfiles2 ec2 instance in AWS

It looks like I can attach the large volume now:

<img width="1645" alt="screen shot 2016-04-14 at 12 30 02 pm" src="https://cloud.githubusercontent.com/assets/2165796/14535654/ccfdcfb2-023c-11e6-9f0f-ee0e5d5ca436.png">

Should I do it now, or just wait to do it in Terminal later?

**Comment by leobardoramon** [comment]
also, should it be set to "Delete on Termination"?

**Comment by gosha1128** [comment]
I don't know :)

**Comment by leobardoramon** [comment]
I said "yes" :)

Question:  Why do RDS instance and EC2 instance have separate VPCs?

**Comment by gosha1128** [comment]
mmm...not sure...is that how we set them up ?

-g

**Comment by leobardoramon** [comment]
This is how it is currently set up, so I am assuming that is how it should be - just double checking.

I just edited the devfiles2/etc/exports file and I'm getting this:
<img width="1196" alt="screen shot 2016-04-14 at 6 09 12 pm" src="https://cloud.githubusercontent.com/assets/2165796/14545337/37bd3444-026c-11e6-851e-011ec4d2ff98.png">

**Comment by gosha1128** [comment]
One of the ip addresses seems to be missing a net mask...

-g

**Comment by leobardoramon** [comment]
I'm following these steps right now:
>http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-using-volumes.html

Because these instructions aren't EXACTLY for our scenario, I'm hesitating ; I've previously had issues with creating what appears to be a redundant directory ( See issue #568 comment @ March 15, 21:50 EDT )

This is what I see now in devfiles2:

<img width="1646" alt="screen shot 2016-04-14 at 9 00 16 pm" src="https://cloud.githubusercontent.com/assets/2165796/14548333/ef1fa9ca-0283-11e6-8c96-8cfa3a501ee9.png">

**Comment by leobardoramon** [comment]
Also, this is what I see in dev6 ( 54.84.48.38 ) development server:
<img width="1089" alt="screen shot 2016-04-14 at 9 03 22 pm" src="https://cloud.githubusercontent.com/assets/2165796/14548403/8fcf24d6-0284-11e6-9de8-233e46c18468.png">

**Comment by gosha1128** [comment]
The last thing is a SQL connection error.

The node web server can't connect to the SQL server.

If I recall, you must set the proper firewall settings at RDS...

-g

**Comment by leobardoramon** [comment]
dev6 IP added to inbound rds rules

**Comment by leobardoramon** [comment]
IP: 54.84.48.38
pem: PROD1.pem
login: leo
pw:  l6shooter

smoke test: Projects>file(s)>upload file
outcome: failed
![screen shot 2016-04-14 at 8 02 58 pm](https://cloud.githubusercontent.com/assets/2165796/14550320/75d9ad60-027c-11e6-9540-cac97224a0bf.png)
![screen shot 2016-04-14 at 8 03 01 pm](https://cloud.githubusercontent.com/assets/2165796/14550321/75de962c-027c-11e6-8afb-649441ef72ce.png)

**Comment by gosha1128** [comment]
OK !

Delete that directory it is complaining about (FILES/1229) and restart
everything and redo your test.

**Comment by leobardoramon** [comment]
I don't think the volume is mounted yet.

How do I find that out?

**Comment by leobardoramon** [comment]
![screen shot 2016-04-14 at 9 15 13 pm](https://cloud.githubusercontent.com/assets/2165796/14551301/1651d5c0-0286-11e6-9f9e-c6711ee6c534.png)

**Comment by gosha1128** [comment]
Yes, now you need to mount the files server on this EBS machine.

Do you know how to do that ?

-g

**Comment by leobardoramon** [comment]
this is what I used last time:
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-using-volumes.html

Do you have easier instructions?

**Comment by gosha1128** [comment]
OK, here is the chain of connection.  Its a lot of stuff....

** browser* runs on *client machine* in ams lab
*that *client machine* also connects directly to a *file server machine*

** browser *connects to *EBS machine*
** EBS machine *connects directly to the same as client machine above *file
server machine*

** file server machine *is directly attached to an attached *volume*

** EBS machine *does not attach to *volume*, but mounts it via NFS exported
by *file server machine*

So for the last thing to work you need to:

0) make sure the *EBS machine* can see to the *file server machine *via
your firewall rules

1) make sure *file server machine */etc/exports file mentions the *EBS
machine*'s ip address ( this means that the* file server machine* will
allow file requests from the *EBS machine* )

2) make sure *file server machine* is exporting the directories mentioned
in the export file ( i think you've done this already - basically there is
something in the file which says "please export /amsfiles" )

3) on the *EBS machine*, mount the exported directory from the *file server
machine *( typically this is done via the /etc/fstab file and the mount
command - let me know if you need help with that )

Again, the EBS machine does not attach the volume.

**Comment by leobardoramon** [comment]
volume appears to be mounted :)
<img width="1220" alt="screen shot 2016-04-18 at 9 37 24 pm" src="https://cloud.githubusercontent.com/assets/2165796/14625078/f3fe194a-05ad-11e6-8424-7aadaf001d3c.png">

A little stuck with making sure that the /etc/fstab file is configure properly.  I tried AWS instruction recommendation:

<img width="877" alt="screen shot 2016-04-18 at 9 47 25 pm" src="https://cloud.githubusercontent.com/assets/2165796/14625373/899e6cdc-05b0-11e6-8dc5-84215bec8bef.png">

 some info is missing though.  So I'm leaving it the way it was:

<img width="578" alt="screen shot 2016-04-18 at 9 44 52 pm" src="https://cloud.githubusercontent.com/assets/2165796/14625391/a4d02428-05b0-11e6-879e-e1c1881b5896.png">

**Comment by leobardoramon** [comment]
I tried uploading a file...that did not go so well
<img width="1105" alt="screen shot 2016-04-18 at 9 53 51 pm" src="https://cloud.githubusercontent.com/assets/2165796/14625399/b70c4d06-05b0-11e6-8ed0-1345c8d1db29.png">

I successfully mounted the devfiles server ( 54.85.47.80 ) to the LGS machine:

<img width="778" alt="screen shot 2016-04-18 at 10 09 59 pm" src="https://cloud.githubusercontent.com/assets/2165796/14625576/5504c780-05b2-11e6-82c0-118a345e9560.png">

I tried downloading a file from Projects>file(s) , that failed:

<img width="1166" alt="screen shot 2016-04-18 at 10 06 40 pm" src="https://cloud.githubusercontent.com/assets/2165796/14625553/1acb34e6-05b2-11e6-8176-d9b7722544c1.png">

Should these be new GH issues?

**Comment by leobardoramon** [comment]
Most obvious difference between "PRODFILES" and "devfiles" for me:

<img width="803" alt="screen shot 2016-04-18 at 10 17 54 pm" src="https://cloud.githubusercontent.com/assets/2165796/14625717/8806e8ce-05b3-11e6-85c5-0bf744d2d9a7.png">
<img width="793" alt="screen shot 2016-04-18 at 10 18 03 pm" src="https://cloud.githubusercontent.com/assets/2165796/14625718/88071b78-05b3-11e6-99a5-a557b2bf708b.png">

**Comment by leobardoramon** [comment]
Smoke Test  :  SUCCESSFUL
https://drive.google.com/open?id=1m_TuEsNDErwxOPDpVN5uwoOcJOgWfx73-iTHG0SrU-o

**Comment by leobardoramon** [comment]
Everything looks good.  Closing for now.

dev - 54.84.48.38
devfiles - 54.85.47.80
dev3 (rds) - dev3.cdsq90t3hkch.us-east-1.rds.amazonaws.com

**Comment by leobardoramon** [comment]
dev credentials doc:
https://drive.google.com/open?id=1x3WhcGnRmNKjBP9ykTu6jIv6m6GowZx1y6SrBGpfsXk
