### ISSUE TITLE
AWS: QA System(s)

### ISSUE THREAD

**Issue by leobardoramon** [gosha1128/NYUAMS#563]
When dev is ready for testing:

Leo will create an image of dev and launch that as a QA instance.

Will QA need it's own RDS instance?

**Comment by gosha1128** [comment]
You'll want to start with the same data for each new test, so yes.

**Comment by leobardoramon** [comment]
Leo will go through environment setup with Andrew and Wilson sometime in the next two weeks.

**Comment by leobardoramon** [comment]
We're almost ready for QA Testing...

1a) we need is to clone over the DEV system into a separate QA environment.

 b) George, can we have the DEV environment in a state for cloning on either Monday or Tuesday?

**Comment by gosha1128** [comment]
Yes, let me know the exact day.  At this point i'm not doing an work in the
admin area, but in queue - and you aren't testing that yet...

**Comment by leobardoramon** [comment]
George, 

I would like to spend Friday cloning DEV over to a QA environment. I'll let you know exact times once i get confirmation from Andrew.

**Comment by gosha1128** [comment]
Yes sounds good.  Just give me the times I need to be available on-line...

-g

**Comment by leobardoramon** [comment]
We'll be cloning server and data images tomorrow morning between the hours of 09:00 - 12:00 EDT.

**Comment by leobardoramon** [comment]
We will be setting up the QA env with the use of an Elastic File System ( EFS )

**Comment by leobardoramon** [comment]
Everything went well.  We decided to forego the EFS for this environment...we will implement the EFS in the next DEV environment.

See troubleshooting doc related to #617 : 
https://docs.google.com/document/d/19uUZvb5rhezMZEpGZGjMxH4G5vNo-ihCW33WMoCl5kQ/edit
