### ISSUE TITLE
AWS:  Security Groups - Valid IP Addresses

### ISSUE THREAD

**Issue by leobardoramon** [gosha1128/NYUAMS#564]
George,

I'm making sure that all machines only accept connections from valid ip addresses.

Are there any prerequisite IP addresses that need to be in the "inbound" protocol?
  - aside from Port Range 80
  - aside from Port Range 22

**Comment by gosha1128** [comment]
Yes...i think the following should work:

1.  For EBS ec2 machines, allow only traffic from machines that will use
the web interface

2.  For FILE SERVER ec2 machines, allow only traffic from machines that
will use the web interface

Also, i was just thinking - for the DEV system, you must also replicate the
FILE SERVER !

-g

**Comment by leobardoramon** [comment]
Thank you.  Closing issue
