### ISSUE TITLE
Data Base is down.   

### ISSUE THREAD

**Issue by buck0land** [gosha1128/NYUAMS#565]
Both EC2 systems in the load balancer are off line.   were you guys working on the system last nigth around 7pm?   

![screen shot 2016-03-08 at 9 31 28 am](https://cloud.githubusercontent.com/assets/17555825/13604426/9885b96e-e510-11e5-9bde-4b4aa921800d.png)
![screen shot 2016-03-08 at 9 32 01 am](https://cloud.githubusercontent.com/assets/17555825/13604437/a1b761d6-e510-11e5-94eb-0112c3a72fe2.png)

**Comment by buck0land** [comment]
So I have restarted prod3, prod4 and prodfiles and still have nothing. it look like the app is crashing on startup

![screen shot 2016-03-08 at 10 35 34 am](https://cloud.githubusercontent.com/assets/17555825/13606373/c0f11a16-e519-11e5-88e5-5549518aef30.png)
![screen shot 2016-03-08 at 10 37 31 am](https://cloud.githubusercontent.com/assets/17555825/13606392/cdba20f8-e519-11e5-885c-ef1938cc7575.png)

**Comment by gosha1128** [comment]
I asked Leo to make sure your firewall was set up properly so probably
something there

**Comment by gosha1128** [comment]
You should wait for him to respond before doing anything drastic

**Comment by gosha1128** [comment]
Can you start the ebs server in interactive mode and paste output here ?

node app.js nfs

Instead of "forever..."

**Comment by gosha1128** [comment]
Can you mount the prod files machine at the workstation ?

**Comment by buck0land** [comment]
ubuntu@ip-10-0-0-87:~$ sudo forever stopall
sudo: unable to resolve host ip-10-0-0-87
info:    Forever stopped processes:
data:        uid  command             script forever pid   id logfile                        uptime      
data:    [0] On5U /usr/local/bin/node app.js 3400    18162    /home/ubuntu/.forever/On5U.log 0:0:0:0.972 
data:    [1] z-8F /usr/local/bin/node app.js 17424   18153    /home/ubuntu/.forever/z-8F.log 0:0:0:3.396 
ubuntu@ip-10-0-0-87:~$ cd /opt/NYUAMS/node/ebs
ubuntu@ip-10-0-0-87:/opt/NYUAMS/node/ebs$ node app.js nfs
WARNING: db: check db exists...
Executing (default): SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'ebs';
WARNING: db: got dbexists-> true
Executing (default): SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'ebs';
WARNING: sql: table count [ { 'COUNT(*)': 35 } ] 35
WARNING: db: dbexists, dbempty -> true false
WARNING: db: not initializing db...
WARNING: db: before all module inits, do_init= false
ERROR: Cannot init db. { [Error: UNKNOWN, unknown error '/amsfiles/EBSFILES/SESSIONS']
  errno: -1,
  code: 'UNKNOWN',
  path: '/amsfiles/EBSFILES/SESSIONS',
  syscall: 'mkdir' }
ubuntu@ip-10-0-0-87:/opt/NYUAMS/node/ebs$

**Comment by buck0land** [comment]
yes the amsflies will mount on the systems here

**Comment by buck0land** [comment]
the load balancer is not finding anything at port 80
![screen shot 2016-03-08 at 11 56 08 am](https://cloud.githubusercontent.com/assets/17555825/13608925/d4beed7e-e524-11e5-9f23-7eeacf82f18f.png)

**Comment by gosha1128** [comment]
The ebs server itself can't locate prodfiles or rds...assuming firewall
rules were updated...i forgot to mention that the rds port and nfs
ports..my bad

**Comment by gosha1128** [comment]
i'll work with Leo to address this when he is at the lab

**Comment by leobardoramon** [comment]
1:
Question:  Should PRODFILES ec2 instace be pointed to RDS instance security group?

<img width="1591" alt="screen shot 2016-03-08 at 1 09 31 pm" src="https://cloud.githubusercontent.com/assets/2165796/13611184/2d435ebc-e52f-11e5-9e43-5885310acaf8.png">


2:
I requested an AMI of PRODFILES ( called devfiles ) 5 minutes before the beginning of all these issues

Does this look like it may be related?

<img width="1590" alt="screen shot 2016-03-08 at 1 04 00 pm" src="https://cloud.githubusercontent.com/assets/2165796/13611039/7f9852ae-e52e-11e5-95f1-2184b318a9db.png">

attachment of forwarded email to follow

**Comment by leobardoramon** [comment]
<img width="1995" alt="screen shot 2016-03-08 at 1 14 48 pm" src="https://cloud.githubusercontent.com/assets/2165796/13611306/e634ad68-e52f-11e5-9e4f-e9543c72aa1d.png">
<img width="1677" alt="screen shot 2016-03-08 at 1 15 23 pm" src="https://cloud.githubusercontent.com/assets/2165796/13611307/e63503a8-e52f-11e5-8155-1faa161a1485.png">
<img width="1742" alt="screen shot 2016-03-08 at 1 15 41 pm" src="https://cloud.githubusercontent.com/assets/2165796/13611308/e6353ae4-e52f-11e5-8265-2a8399eeff4a.png">

**Comment by gosha1128** [comment]
Yes its likely the issue.

You need to go to an EBS prod system and try to mount the file system
manually at the command line:

I believe this should work:

>>sudo bash
>>mount /amsfiles

It will probably hang and eventually give you an error.

Also what does the exports file look like?  I assume you didn't change
that.  The information in that file is used to figure out how to mount
/amsfiles.



-g

**Comment by leobardoramon** [comment]
<img width="719" alt="screen shot 2016-03-08 at 1 23 58 pm" src="https://cloud.githubusercontent.com/assets/2165796/13611531/16ca87ee-e531-11e5-9e22-0d7664fea7e3.png">

**Comment by gosha1128** [comment]
Great.  What does the exports file look like ?

-g

**Comment by leobardoramon** [comment]
Where is that located, please?

andrew had me run a couple of commands.  is this helpful info?

<img width="938" alt="screen shot 2016-03-08 at 1 25 41 pm" src="https://cloud.githubusercontent.com/assets/2165796/13611626/7d8af86a-e531-11e5-9262-8abf1dd573c8.png">

**Comment by gosha1128** [comment]
Great, these are the active "mount" points.  A mount point is the "bridge"
to the other machine (in our case PROD FILES).

So it doesn't appear that /amsfiles is active.

Now, lets see where the mount points are configured.  Paste here the
contents of the file /etc/exports...

**Comment by leobardoramon** [comment]
PRODFILES, 52.6.228.88/etc/exports

<img width="953" alt="screen shot 2016-03-08 at 1 30 27 pm" src="https://cloud.githubusercontent.com/assets/2165796/13611729/f2d14c46-e531-11e5-9f94-b0483dbdcfff.png">

**Comment by gosha1128** [comment]
OK, i'm sorry i should be very clear:

There are two parts to this:  The client of an exported file system ( any
EBS server ) and the server of an exported file system ( PROD FILES ).

For the client, investigate as follows:
* you would run "mount /amsfiles"
* if there is an error or issue, you would look at /etc/fstab to see which
server it is trying to mount to for /amsfiles


For the server, investigate as follows
* you would restart nfs ( i think i sent you this before )
* if there is an error or issue,  you would look at /etc/exports to see
what machines (ip addresses) can access the exported filesystem
* verify that all other machines that should be able to see the exported
file system are listed (either through ip address or address range syntax )

**Comment by leobardoramon** [comment]
IP addresses for PROD3 & PROD4 are not listed in [PRODFILES]/etc/exports file,

Should I add them now?

**Comment by gosha1128** [comment]
Are PROD3 and PROD4 EBS servers ?

If yes, then yes you can add the ip addresses directly.

Better than that would be an ip address range.  That way, new machines that
you create in the future in the same range would just work and you don't
have to add individual machine ip addresses.

Just google NFS exports address range for the correct syntax for the
exports file.

Remember that whenever you change the exports file you need to restart NFS
at PROD FILES.

-g

**Comment by gosha1128** [comment]
For now, just add the ip addresses and see if that works.

You can always do address range later...

-g

**Comment by leobardoramon** [comment]
*[ PROD3 , PROD4 ] IP Address added to:
-[PRODFILES]/etc/exports file
-[AWS]/PRODFILES/security group inbound rules
   - UDP
<img width="1045" alt="screen shot 2016-03-08 at 2 14 34 pm" src="https://cloud.githubusercontent.com/assets/2165796/13613243/529ace2a-e539-11e5-844f-52cf74459ef9.png">
<img width="1633" alt="screen shot 2016-03-08 at 2 20 35 pm" src="https://cloud.githubusercontent.com/assets/2165796/13613244/529b4620-e539-11e5-8f31-3216c4d6ec81.png">

still getting "Stale file handle" message when running "mount /amsfiles" from ec2 instance PROD3 via Terminal
<img width="935" alt="screen shot 2016-03-08 at 2 12 23 pm" src="https://cloud.githubusercontent.com/assets/2165796/13613276/68657caa-e539-11e5-86dc-b27a38376fc1.png">

**Comment by gosha1128** [comment]
Yeah...this is never easy.

Next try unmounting /amsfiles

>> umount /amsfiles

Then mount

>> mount /amsfiles

**Comment by leobardoramon** [comment]
the EBS is live

<img width="555" alt="screen shot 2016-03-08 at 2 50 56 pm" src="https://cloud.githubusercontent.com/assets/2165796/13614202/5e02faae-e53d-11e5-96dc-73dd3591e6f6.png">
<img width="959" alt="screen shot 2016-03-08 at 2 51 19 pm" src="https://cloud.githubusercontent.com/assets/2165796/13614201/5e02a41e-e53d-11e5-9995-c034c5a87ad6.png">
<img width="1092" alt="screen shot 2016-03-08 at 2 52 05 pm" src="https://cloud.githubusercontent.com/assets/2165796/13614204/5e0454b2-e53d-11e5-9ac4-3be7086243d0.png">
<img width="932" alt="screen shot 2016-03-08 at 2 52 11 pm" src="https://cloud.githubusercontent.com/assets/2165796/13614203/5e035350-e53d-11e5-9574-01b5b809776d.png">

**Comment by leobardoramon** [comment]
What is the next step?
  - aside from documenting this troubleshooting workflow

**Comment by gosha1128** [comment]
Yes, you should go back through this issue and create a trouble shooting
document, eventually.  I think just create an issue for yourself and
prioritize it accordingly.  For example, make it easy so that an AMS staff
could follow it ( do not put any passwords in the document - instead, just
say speak to Leo, Andrew, etc, for passwords...)

-g

**Comment by leobardoramon** [comment]
Closing issue.

Please refer to issue #567
