### ISSUE TITLE
Test Case:  Projects>file(s)> upload file

### ISSUE THREAD

**Issue by leobardoramon** [gosha1128/NYUAMS#568]
even though my machine is connected to the file server, I'm not able to upload a file

stuck at "100%"

<img width="1286" alt="screen shot 2016-03-14 at 3 22 59 pm" src="https://cloud.githubusercontent.com/assets/2165796/13756962/b278b6b8-e9f8-11e5-9054-5c846388b6bb.png">

**Comment by gosha1128** [comment]
This is likely related to RDS being out of sync with the production files :)

Here is what you do when you see this:

1)  restart EBS server in manual mode

2)  do the upload again

3)  likely there was an error - paste it here

**Comment by leobardoramon** [comment]
<img width="1096" alt="screen shot 2016-03-14 at 3 33 41 pm" src="https://cloud.githubusercontent.com/assets/2165796/13757301/315d6266-e9fa-11e5-82a4-1fd6ba003256.png">

**Comment by gosha1128** [comment]
OK, this will happen with files server is out of sync with RDS.

You will need to login to the files server machine.

Delete the directory at /amsfiles/EBSFILES/FILES/1002

and try again.

**Comment by leobardoramon** [comment]
1.  how do I find this directory?
   - see attachment
2.  once I find it, is this the command I use:
   - sudo bash
   - rm -rf 1002
?

<img width="2560" alt="screen shot 2016-03-14 at 4 36 11 pm" src="https://cloud.githubusercontent.com/assets/2165796/13759127/3a625516-ea03-11e5-995b-70f9c06a7851.png">

**Comment by gosha1128** [comment]
sudo bash

cd /amsfiles/EBSFILES/FILES/

rm -fr 1002

**Comment by leobardoramon** [comment]
<img width="471" alt="screen shot 2016-03-14 at 4 44 18 pm" src="https://cloud.githubusercontent.com/assets/2165796/13759311/0afd5748-ea04-11e5-9cdd-74ab0c88f1ce.png">

**Comment by gosha1128** [comment]
what is in /amsfiles ?

**Comment by leobardoramon** [comment]
It shows me nothing...I thought it was just invisible
<img width="615" alt="screen shot 2016-03-14 at 5 30 41 pm" src="https://cloud.githubusercontent.com/assets/2165796/13760627/81b5a2a4-ea0a-11e5-94f7-fbe77fd9d3b0.png">

**Comment by gosha1128** [comment]
OK, so it sounds like the actual VOLUME is not mounted on the file server.

Yes, there is yet another step.

Please attach the contents of /etc/fstab of dev files.

Also, please attach the contents of /etc/fstab for prod files, so that we
can compare to a working system.

**Comment by gosha1128** [comment]
You should be able to following the directions here:

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-using-volumes.html

NOTE: IMPORTANT:  These are very dangerous operations as you could easily
delete ALL files on a file server.   If you are on a production file ec2
instance - then make sure you have a recent backup of files.  If you are on
a dev system - make damn sure you are on a dev instance and not production
:)

**Comment by leobardoramon** [comment]
![screen shot 2016-03-15 at 10 28 08 am](https://cloud.githubusercontent.com/assets/2165796/13781217/f5972d94-ea98-11e5-9e18-28f4c33ff85e.png)

**Comment by gosha1128** [comment]
Great.  Now you just need to mount the VOLUME which has the copy of the
prod files data.

A VOLUME is file storage directly attached to the EC2 machine and it needs
to be mounted.

This is different than the /exports stuff - that is NFS and it makes the
data on the volume available to other machines.

Subtle different, but its important.

**Comment by leobardoramon** [comment]
Great. This will happen tonight or early tomorrow morning

**Comment by leobardoramon** [comment]
from "devfiles" via Terminal:
>lsblk
![screen shot 2016-03-15 at 5 53 46 pm](https://cloud.githubusercontent.com/assets/2165796/13795409/f022784e-ead6-11e5-9817-c388e92c9c24.png)

**Comment by gosha1128** [comment]
Yes, it looks like "XVDF" is the one with your data ( given the size 3.9T ).

The other is just the system volume - which contains the operating system.

Its typical to have multiple volumes attached to one machine, in this way...

-g

**Comment by leobardoramon** [comment]
Step 3. ( from devfiles/EBSFILES/ )
>sudo mkdir devfiles_volume
>sudo mount /dev/xvdf devfiles_volume

<img width="1011" alt="screen shot 2016-03-15 at 9 30 33 pm" src="https://cloud.githubusercontent.com/assets/2165796/13799460/e57d11aa-eaf5-11e5-89a3-744bc5cf9d96.png">

Step 4.
>sudo cp /etc/fstab /etc/fstab.orig

<img width="986" alt="screen shot 2016-03-15 at 9 30 46 pm" src="https://cloud.githubusercontent.com/assets/2165796/13799457/e0d36424-eaf5-11e5-9fc4-4ed2570fd282.png">

Step 5.
Since it's optional, I'm skipping this step

<img width="879" alt="screen shot 2016-03-15 at 9 43 03 pm" src="https://cloud.githubusercontent.com/assets/2165796/13799577/09a9d9c2-eaf7-11e5-98ee-677379a88e3d.png">

it looks like this has already been set from PRODFILES

QUESTION:  should I modify this so that it does not resemble PRODFILES?

Step 6. Not sure about this part...

<img width="879" alt="screen shot 2016-03-15 at 9 43 03 pm" src="https://cloud.githubusercontent.com/assets/2165796/13799636/c8842eba-eaf7-11e5-9aae-cfc07b0494c0.png">

I tried those commands, but I don't know how to verify

<img width="509" alt="screen shot 2016-03-15 at 9 50 07 pm" src="https://cloud.githubusercontent.com/assets/2165796/13799656/ea9811ce-eaf7-11e5-9ce5-2a92603020a8.png">

**Comment by leobardoramon** [comment]
testing file upload now...

**Comment by leobardoramon** [comment]
File still not uploading, similar issue (instead of dir ".../1002/" it is now dir ".../1003/" ) not exactly sure what's happening
left - devfiles ( 52.23.240.139 )
right - dev4 ( 54.165.224.16 )

<img width="1386" alt="screen shot 2016-03-15 at 9 55 54 pm" src="https://cloud.githubusercontent.com/assets/2165796/13799756/db90aa96-eaf8-11e5-9526-8ea8ba06a0a1.png">
<img width="2260" alt="screen shot 2016-03-15 at 9 55 44 pm" src="https://cloud.githubusercontent.com/assets/2165796/13799760/de279a58-eaf8-11e5-8a88-2dac2012fcf5.png">

**Comment by leobardoramon** [comment]
this is how I'm leave dev4 ( 54.165.224.16 )

<img width="651" alt="screen shot 2016-03-15 at 10 07 24 pm" src="https://cloud.githubusercontent.com/assets/2165796/13799942/885d5fb6-eafa-11e5-8b70-63d445ea126e.png">
<img width="1463" alt="screen shot 2016-03-15 at 10 07 39 pm" src="https://cloud.githubusercontent.com/assets/2165796/13799943/885ddafe-eafa-11e5-89c5-055f084053ac.png">

**Comment by gosha1128** [comment]
OK, do this:

Go to PROD FILES and show me the contents of /etc/fstab

Also, what is the output of this command:

>> ls /amsfiles

**Comment by gosha1128** [comment]
Also, go into the EC2 console.

What is the file system type for the VOLUME that is attached to PROD FILES ?

**Comment by leobardoramon** [comment]
>cat /etc/fstab

![screen shot 2016-03-16 at 12 14 50 pm](https://cloud.githubusercontent.com/assets/2165796/13825644/ce0098e6-eb70-11e5-9cb5-c62b74946d42.png)

>ls /amsfiles

![screen shot 2016-03-16 at 12 16 17 pm](https://cloud.githubusercontent.com/assets/2165796/13825685/f9fa626a-eb70-11e5-87db-b8a20517e1d7.png)

 - there are 2 volumes for PRODFILES

![screen shot 2016-03-16 at 12 20 49 pm](https://cloud.githubusercontent.com/assets/2165796/13825835/bddbc8a4-eb71-11e5-933f-9845c679adc3.png)
![screen shot 2016-03-16 at 12 21 13 pm](https://cloud.githubusercontent.com/assets/2165796/13825834/bdc1d1f6-eb71-11e5-8b3e-fb35d24a5fc4.png)
![screen shot 2016-03-16 at 12 21 42 pm](https://cloud.githubusercontent.com/assets/2165796/13825833/bdc19a10-eb71-11e5-96b3-a1c432229f07.png)

**Comment by gosha1128** [comment]
Great, so PROD FILES has two volumes attached.  One for the file system
(small 8G) and the other for data (big 4000GB).  The latter one is the
where the files data lives ( i.e., its "mounted" at the location called
"/amsfiles" )

It looks like I manually mounted it.  I should have also put it into
/etc/fstab so that on any reboot the system knows what to do - but lets
return to that later.)

So, on PROD FILES we want to see how the two VOLUMES are mounted right now.

To do this type the following:

>> sudo df

And append it here

**Comment by leobardoramon** [comment]
![screen shot 2016-03-16 at 12 21 42 pm](https://cloud.githubusercontent.com/assets/2165796/13831831/cccb11ae-eb93-11e5-897b-ba67c9b1856a.png)

**Comment by leobardoramon** [comment]
PRODFILES
>sudo df
![screen shot 2016-03-16 at 4 25 46 pm](https://cloud.githubusercontent.com/assets/2165796/13831904/5258f16a-eb94-11e5-8ac0-2e3a18f7f777.png)

**Comment by gosha1128** [comment]
OK, as you can see - the VOLUME with all the data is mounted at the
location /amsfiles.

The VOLUME has a device name of /dev/xvdf.

--

So, we want to do the same at the DEV files.

Also, locate the VOLUMES attached to the DEV files machine via EC2 console.

Likely there are two VOLUMES as well, a small one and a big one.

Can you check that ?

**Comment by gosha1128** [comment]
Once you do all that, look at the following site-
http://maplpro.blogspot.com/2012/05/how-to-mount-ebs-volume-into-ec2-ubuntu.html

*Do not FORMAT the volume since it is already formatted ( so skip that
step. )  Everything else looks right:*



>> sudo fdisk -l
Disk /dev/xvdf: 10.7 GB, 10737418240 bytes

Then format it (if you haven't already done it)
>> sudo mkfs -t ext4 /dev/xvdf

Create dir where it will be mounted:
>>mkdir /mnt

That's it you can mount it:
>>sudo mount /dev/xvdf /mnt

Check if it has been mounted correctly with:
>>mount -l
/dev/xvdf on /mnt type ext4 (rw)

Make it to mount automatically on system start
>>sudo vim  /etc/fstab

and add this:
/dev/xvdf       /mnt1   auto    defaults,nobootwait     0       0

Done

BTW by some reason AWS Console shows /dev/xvdf as /dev/sdf

**Comment by leobardoramon** [comment]
This will get done tomorrow at 9am pst

**Comment by leobardoramon** [comment]
George,

I'm having trouble...can I start over...or trace back a few steps?

# My issue:
when I mounted the devfiles volume on Wednesday I accidentally made an extra directory with the same name ( EBSFILES ).  I think that is giving me trouble, I tried moving the sub-directory "devfiles_volume" into the main directory "/home/" and "/ubuntu/home/" and I wasn't allowed.

I think this needs to be resolved before moving forward.

I'm getting notifications that directories and files already exist.

# See below:

![screen shot 2016-03-18 at 10 52 30 am](https://cloud.githubusercontent.com/assets/2165796/13887749/b8683e9a-ecfa-11e5-9edd-9ee1d4a3e3b6.png)

----
# My Steps

Step 1.
 - >sudo fdisk -l
 - Disk /dev/xvdf: 4295.0 GB, 4294967296000 bytes
255 heads, 63 sectors/track, 522166 cylinders, total 8388608000 sectors

![screen shot 2016-03-18 at 10 52 30 am](https://cloud.githubusercontent.com/assets/2165796/13887183/9948ac82-ecf7-11e5-8017-4c5b4469a430.png)

Step 2. Create dir where it will be mounted 
 - >mkdir /mnt

----

# *Other Notes

Where PRODFILES has the directory "/amsfiles" , devfiles has "/home/ubuntu/EBSFILES/"
  - can we simplify this easily for "devfiles" ( 52.23.240.139 )?
  - the portion "/home/ubuntu/EBSFILES/" of "/home/ubuntu/EBSFILES/devfiles_volume/EBSFILES/" seems redundant

![screen shot 2016-03-18 at 10 34 09 am](https://cloud.githubusercontent.com/assets/2165796/13886885/5f143e06-ecf6-11e5-91aa-02ea214339aa.png)

**Comment by gosha1128** [comment]
OK, it looks like FDISK might be the wrong utility.

Try this and paste the output:

sudo parted -l

**Comment by leobardoramon** [comment]
![screen shot 2016-03-18 at 12 40 12 pm](https://cloud.githubusercontent.com/assets/2165796/13890020/99b7a10a-ed06-11e5-81a0-5205c6c69974.png)

**Comment by gosha1128** [comment]
thats fine.  i should have said do mkdir if directory does not exit

**Comment by gosha1128** [comment]
exist

On Fri, Mar 18, 2016 at 12:48 PM, George Williams <george.williams@gmail.com

**Comment by leobardoramon** [comment]
![screen shot 2016-03-18 at 12 50 13 pm](https://cloud.githubusercontent.com/assets/2165796/13890355/3364a202-ed08-11e5-9104-9d9029084f68.png)

**Comment by leobardoramon** [comment]
![screen shot 2016-03-18 at 12 50 13 pm](https://cloud.githubusercontent.com/assets/2165796/13890372/4ef94e64-ed08-11e5-87bc-e932e4ce2104.png)

**Comment by leobardoramon** [comment]
point-in-time Snapshot of PRODFILES volume will be schedule for sometime tomorrow morning ( 00:00 - 06:00 PST ).

Andrew & Shelly, please approve this request & please notify the staff of the following information:

AMS Staff,

This is a notification that our Enterprise Business System (EBS) database will be unavailable between:

**12:00am 3/19 - 12:00am 3/22
**
Please let us know if you have any questions.  Please email us immediately regarding any database issues ( info@codetodesign.com OR leo@codetodesign.com )

Have a great weekend,


Leobardo Martinez
Code To Design
leo@codetodesing.com

**Comment by leobardoramon** [comment]
* leo@codetodesign.com

**Comment by leobardoramon** [comment]
George,

It looks like Point In Time Recovery isn't available in the AWS console for *Volume* Snapshots.

Should I:

(a) take new snapshots of RDS Instance, and devfiles Volume

(b) take new snapshots of RDS Instance, PRODFILES Volume , PRODFILES ec2 instance

(c) new snapshots of everything

(d) see if there's a way to do Point In Time Volume Snapshots via Terminal

![screen shot 2016-03-19 at 12 21 32 pm](https://cloud.githubusercontent.com/assets/2165796/13900902/760ad358-edce-11e5-890b-052d5bc7ee72.png)

**Comment by gosha1128** [comment]
Yes, it looks like you will have to use the CLI.

Since you are a master at the command line, this shouldn't be a problem :)

First - you should decide between the AWS CLI or the Amazon EC2 CLI ( I
don't remember the difference ), so you should read up on this.  Maybe
google "aws cli vs ec2 cli".

One you decide and get the proper tools on the machine, then follow the
directions you found.

Let me know if you have any problems.

**Comment by leobardoramon** [comment]
George,

Can I go with AWS CLI?

AWS CLI is newer and is Python based rather than Java based

![screen shot 2016-03-20 at 6 53 38 pm](https://cloud.githubusercontent.com/assets/2165796/13909311/95e1d06e-eecd-11e5-9737-f6f7e0f7963f.png)
![screen shot 2016-03-20 at 6 54 46 pm](https://cloud.githubusercontent.com/assets/2165796/13909312/95eeb310-eecd-11e5-9075-7ea5a9ed9c3d.png)

See Tech Republic article:
http://www.techrepublic.com/article/good-reasons-to-install-the-new-aws-cli-tools-on-a-vm-on-amazon-ec2/

**Comment by gosha1128** [comment]
Yep, that sounds right.

**Comment by leobardoramon** [comment]
following these instructions:

![screen shot 2016-03-20 at 10 11 32 pm](https://cloud.githubusercontent.com/assets/2165796/13911047/c35d580e-eee8-11e5-89ec-78c84210bbaf.png)
![screen shot 2016-03-20 at 10 11 44 pm](https://cloud.githubusercontent.com/assets/2165796/13911048/c36d842c-eee8-11e5-85f2-71f6c823c489.png)


http://docs.aws.amazon.com/cli/latest/userguide/installing.html

**Comment by gosha1128** [comment]
Yes, thats right.

**Comment by leobardoramon** [comment]
ATTN:  Andrew,

It looks like Point In Time recovery for Volumes will take longer than I was expecting.

Monday and Tuesday I will be learning how to use the AWS CLI and navigate through custom commands, such as Point In Time Volume recovery.

**Comment by leobardoramon** [comment]
George,

It looks to me that PiT Volume snapshots may not be possible via AWS CLI

Tomorrow I will check on the Snapshot capabilities of ec2 CLI

Update to follow.  Thank you

**Comment by leobardoramon** [comment]
It is not possible.

![screen shot 2016-03-23 at 10 01 36 am](https://cloud.githubusercontent.com/assets/2165796/13993658/7fb2eaf4-f0de-11e5-9a13-b38d901c8fb8.png)
![screen shot 2016-03-23 at 10 01 53 am](https://cloud.githubusercontent.com/assets/2165796/13993659/7fb3b86c-f0de-11e5-9fce-174285ae8798.png)

FYI:  I am scheduling snapshots for tomorrow night, Thursday 3/24 23:00MST

**Comment by gosha1128** [comment]
OK, this just means that when you backup the entire system - you should do
it when no one is using the system - backup both RDS and the files volume
at nearly the same time.

As long as no one is using the system when you do this - then RDS backup
and the volume backup are essentially "in sync".

You should probably match the backup names somewhere ( maybe with a
timestamp in the name ).

When you do a volume backups - make sure its of the "diff" variety.  This
way the size of each backup only represents the "difference" in data
between backups - this keeps the storage cost of low of doing lots of
volume backups.

**Comment by leobardoramon** [comment]
devfiles aka 54.85.47.80

file has been successfully (a) uploaded and (b) downloaded

<img width="1903" alt="screen shot 2016-04-20 at 5 09 02 pm" src="https://cloud.githubusercontent.com/assets/2165796/14690704/62948060-071b-11e6-8b7e-7faff8c98a6d.png">
<img width="2073" alt="screen shot 2016-04-20 at 5 11 37 pm" src="https://cloud.githubusercontent.com/assets/2165796/14690705/6297b2e4-071b-11e6-92e0-56273a3ad0e2.png">

**Comment by leobardoramon** [comment]
closing for now

**Comment by gosha1128** [comment]
WOOHOO !  :) :) :)

**Comment by gosha1128** [comment]
Alright...go ahead and start lining up the bug fixes to be done on DEV...

-g
