### ISSUE TITLE
SSL certificates expiring

### ISSUE THREAD

**Issue by buck0land** [gosha1128/NYUAMS#573]
Did we setup our SSL certificates for prod?  Our certificate will be expiring on the 5/21.  Leo closes this it we never setup the use of the SSL certificates but is if we are using the certificates then let set aside some time and update them.

**Comment by gosha1128** [comment]
They are not set up.  Should be pretty easy for Leo ... Let me know if you
have any questions...

**Comment by leobardoramon** [comment]
George,
Sounds good.

Andrew,
Will you have time for this today?

**Comment by gosha1128** [comment]
If possible, i recommend doing this on DEV first, working out all the
issues, and then doing it to PROD.

Depending on the nature of your SSL certificate ( wildcards or not ), you
might need to map DNS names ( the public names of your server ) to the
public ip address of the machine.

You should google "node SSL express setup".  This looks promising...

http://stackoverflow.com/questions/11804202/how-do-i-setup-a-ssl-certs-for-an-express-js-server

I may need to possibly change some code on DEV to accommodate this.

**Comment by leobardoramon** [comment]
Andrew says that we're not using ssl certification.  This is not relevant to us.

Closing for now
