### ISSUE TITLE
Clone PROD4

### ISSUE THREAD

**Issue by leobardoramon** [gosha1128/NYUAMS#576]
steps to clone PROD4 ( 54.173.186.157 )
https://docs.google.com/document/d/1KG8Wb732aoX0x1_PUcpRx2YZa8ARDc1l6DShGbUg9SQ/edit#

**Comment by leobardoramon** [comment]
I don't want to restart the Prod server PROD4 until the AMI is no longer in a state of "pending"

It's been over two hours.  I'll set an alarm for 07est to see where it's at

**Comment by leobardoramon** [comment]
PROD4 has been successfully cloned and restarted.

**Comment by leobardoramon** [comment]
ec2 instance PROD5 is spinning up now

**Comment by leobardoramon** [comment]
Andrew,

Will you be available tomorrow?  I'd like to add PROD5 to the Load Balancer.

**Comment by leobardoramon** [comment]
Andrew,

I didn't realize you were away last week.  May I add PROD5 to the AWS Load Balancer tonight?  This way we can monitor it tomorrow morning for any irregularities.

George,

Are there any cautionary steps that I should take before adding PROD5 ( created from PROD4 ) to the Load Balancer?

**Comment by gosha1128** [comment]
No, if you creating the new node from the existing clone...you should be
fine.

Remember to do the following:

For version 1...make sure to pull the latest code for that version:

>> cd /opt/NYUAMS/ebs
>> git pull

This will pull from the "master" branch by default...which is essentially
version 1.

**Comment by buck0land** [comment]
it can go live at any point.

-Andrew

On Mon, Jun 13, 2016 at 3:31 PM, leobardoramon <notifications@github.com>
wrote:

> Andrew,
>
> I didn't realize you were away last week. May I add PROD5 to the AWS Load
> Balancer tonight? This way we can monitor it tomorrow morning for any
> irregularities.
>
> George,
>
> Are there any cautionary steps that I should take before adding PROD5 (
> created from PROD4 ) to the Load Balancer?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gosha1128/NYUAMS/issues/576#issuecomment-225683756>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AQvhcWQhyW5ZlfL5nYoI1N29U5qkhbwfks5qLbAugaJpZM4InXl6>
> .
>



-- 
------------------------------------
Andrew Buckland
Technical lead, LaGuardia Studio (LGS)
Senior Advanced Media Specialist
Academic Technology Services, IT

New York University
545 Laguardia Place
New York, New York 10012

Phone:(212)998-3610
email: andrew.buckland@nyu.edu
http://www.nyu.edu/its/ams

**Comment by gosha1128** [comment]
...i should follow up...

Do not pull code from any of the update (i.e., non-master) branches ( don't
worry - you can't accidentally do this ).

The newer branch has speed and performance optimizations that have yet to
be formally tested.

George

On Mon, Jun 13, 2016 at 12:34 PM, George Williams <george.williams@gmail.com

**Comment by leobardoramon** [comment]
*for PROD servers, ONLY pull from "master"

is this correct?

**Comment by gosha1128** [comment]
Yes, that is correct.

If you are starting from a clone, then go into the ebs directory and enter:

>> git pull

which automatically choose the "master" branch

Or you could do it explicitly like so:

>> git pull origin master

Eventually, when we are ready with the new update, you could do it like
this:

>> git pull origin <BRANCH_NAME>

Where <BRANCH_NAME> is the actual name of the branch update.

**Comment by leobardoramon** [comment]
Great, thank you.

George,
I'm getting this message:
<img width="590" alt="screen shot 2016-06-13 at 3 50 05 pm" src="https://cloud.githubusercontent.com/assets/2165796/16021081/c68e6d14-317e-11e6-9849-98928159c157.png">

should I follow these instructions:
<img width="600" alt="screen shot 2016-06-13 at 3 50 38 pm" src="https://cloud.githubusercontent.com/assets/2165796/16021092/d8f35c44-317e-11e6-9563-e64d38d46a82.png">

**Comment by gosha1128** [comment]
Right.  So if you get that message, do the following:

>> git stash save

Then do the git pull.

Then, change the config settings to use your SQL connection string, etc.

Then, do a quick test by starting the server in interactive mode and
testing the web interface against just this server (using ip address.)

If that looks good...then just restart the server in forever mode.

You are done !

-g

**Comment by leobardoramon** [comment]
directory: 52.91.242.118/opt/NYUAMS/node/ebs
1. >git stash save
2. >git pull
3. AWS, add ip address to PRODFILES security group
4. AWS, add ip address to RDS security group
5. verified correct RDS endpoint in /db/config.js 
6. >node app.js nfs
7. interface test of 52.91.242.118
8. >[control]+C
9. >sudo forever start app.js nfs
10. AWS, added Availability Zone C to Load Balancer
11. AWS, added PROD5 to Load Balancer

everything looks good so far.
<img width="1692" alt="screen shot 2016-06-13 at 9 10 25 pm" src="https://cloud.githubusercontent.com/assets/2165796/16028228/501de2f4-31ab-11e6-8c4c-e283409cbac4.png">

**Comment by gosha1128** [comment]
yes thats it !

your smoke/interface test should consist of:

1) test login/password

2) do some basic browsing of projects, contacts, etc

3) do something that requires viewing files ( like pull up an invoice or
something ) - this will test that you have mounted the PRODFILES machine
correctly

4) so something that requires creating a file at PRODFILES ( like
generating an invoice/receipt/etc )

**Comment by leobardoramon** [comment]
Yes, it's all good :)

thank you.

closing for now
