### ISSUE TITLE
AWS: EC2 Instance "dev6" aka 54.84.48.38 may be corrupted...

### ISSUE THREAD

**Issue by leobardoramon** [gosha1128/NYUAMS#579]
ec2 instance "dev6" was being created from the image of PROD3 -without first stopping the server- when the system crashed -due to staff activity.  We believe this is what caused the corruption of PROD3.  It seems only reasonable to suspect corruption of the product image used to spin up "dev6"

I'm only realizing this just now because I am noticing new bugs that have to do with the file server:
(1) viewing pdfs
(2) downloading files

I have spun up a new ec2 instance, "dev7" aka 54.165.240.163 ( from the image of "PROD4" )

George,

If you agree with my assessment, I would like to replace "dev6" with "dev7" as soon as possible so that I can continue testing.

Since you have done optimization work the Dev system, how does this affect the work you have done?

...Do you have to redo your work?

What are the steps I should take?

**Comment by gosha1128** [comment]
Thats fine.

All the code lives in the github branch, all the data lives in either SQL
or the PRODFILES file system.

So nothing important is lost if an EC2 node is lost or deleted.   Do with
those nodes as you please.

-g

**Comment by leobardoramon** [comment]
dev6 terminated

dev7 is live

Closing for now
