### ISSUE TITLE
Test Case:  DEV_smoketest : Projects>file(s)>Add File

### ISSUE THREAD

**Issue by leobardoramon** [gosha1128/NYUAMS#580]
dev7 IP Address:  54.165.240.163
ssh:  ssh -i PROD1.pem ubuntu@54.165.240.163

smoke testing new server
unable to upload file, Error: EEXIST, file already exists

<img width="1421" alt="screen shot 2016-06-16 at 4 00 17 pm" src="https://cloud.githubusercontent.com/assets/2165796/16131329/b24e6c50-33db-11e6-9d6a-93f71be24282.png">

File Download and PDF work correctly

**Comment by gosha1128** [comment]
OK, please try deleting that directory 1256 on the machine PRODFILES and
try again.

The problem is that SQL thinks there is already a file with that ID.

When it goes to actually create it, it finds its already there.

This can happen when a file operation is interrupted/not completed.

We should change to code so this doesn't happen any more, right ?

**Comment by leobardoramon** [comment]
The problem is, that file DOES NOT exist in DEVFILES.  See attached screenshot above of the directory "FILES", the most recent file is "1250"

Just in case this might have been out of sync, I checked the directory directly on the file server via Terminal

see below
<img width="681" alt="screen shot 2016-06-16 at 6 41 31 pm" src="https://cloud.githubusercontent.com/assets/2165796/16135564/5f20456e-33f2-11e6-8f91-ca89455de934.png">

**Comment by gosha1128** [comment]
weird...the error clearly states it thinks it exists...

are you on PRODFILES for the prod or dev ?

**Comment by leobardoramon** [comment]
54.85.47.80 aka DEVFILES

**Comment by gosha1128** [comment]
and you check DEVFILES ?

and you are sure this dev ebs instance has mounted DEVFILES ?

-g

**Comment by leobardoramon** [comment]
Yes, i was able to successfully download files and view invoices from the
devfiles2 fileserver

...i haven't tried to create and invoice. I guess that's the next test.
I'll update you tomorrow

**Comment by leobardoramon** [comment]
I just created an invoice...

so the only problem is file UPLOAD.  The system seems to be confused as to what exists in the FILES directory.

George,

when will you have time to look into this?

**Comment by leobardoramon** [comment]
George,

Is there something I should do? Should I create another clone and retry?

When will you have time to investigate this?

**Comment by gosha1128** [comment]
OK, enter here the exact steps to repro and I will check ( include machine
names, log, pass, etc )

**Comment by leobardoramon** [comment]
# Terminal
## Start Server
- Open a Terminal window
- "cd" into your PROD1.pem directory
- >ssh -i PROD1.pem ubuntu@54.165.240.163
- >sudo forever stopall
- >sudo bash
- >cd /opt/NYUAMS/node/ebs
- >node app.js nfs
## Start Fileproxy Server
- Open a new Terminal window/tab
- >cd <fileproxy dir>/NYUAMS/node/ebs/local
- >sudo killall node
- <enter password>
- >sudo node fileproxy.js
# Chrome
- Launch Chrome
- In Address Bar, type server address: "54.165.240.163"
- Login , "leo"
- Password , "l6shooter"
- Domain , "Local"
- "Sign In"
- Go to "Projects"
- Expand view to Detail View
- Select any project
- Select "file(s)" radio button
- Add any file, any size
# Error
This should give you the Terminal error:

CF args 298 undefined undefined
ABOUT TO CREATE undefined undefined
CCFF undefined undefined
WARNING: upload: cmd-> identify "/tmp/9464-1gdn78q.png"
WARNING: execS: { code: 0,
  stdout: '/tmp/9464-1gdn78q.png PNG 5120x2880 5120x2880+0+0 8-bit DirectClass 14.88MB 0.000u 0:00.000\n' }
WARNING: upload: pts: [ '/tmp/9464-1gdn78q.png',
  'PNG',
  '5120x2880',
  '5120x2880+0+0',
  '8-bit',
  'DirectClass',
  '14.88MB',
  '0.000u',
  '0:00.000\n' ]
WARNING: upload: sizestr: 5120x2880
WARNING: upload: size 5120 2880
WARNING: ps: [ '5120', '2880' ]
Executing (default): INSERT INTO `Files` (`url`,`fmt`,`status`,`deviceid`,`width`,`height`,`asset`,`des`,`name`,`pjp`,`fspath`,`fsdir`,`createdAt`,`updatedAt`) VALUES (NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2016-06-22 17:19:46','2016-06-22 17:19:46');
INFO: sql: SQL new ok.
WARNING: db_file: fdir= /amsfiles/EBSFILES/FILES/1258

/opt/NYUAMS/node/ebs/node_modules/sequelize/node_modules/bluebird/js/main/async.js:79
            throw res.e;
                     ^
Error: EEXIST, file already exists '/amsfiles/EBSFILES/FILES/1258'
    at Object.fs.mkdirSync (fs.js:642:18)
    at /opt/NYUAMS/node/ebs/db/file.js:372:8
    at tryCatch1 (/opt/NYUAMS/node/ebs/node_modules/sequelize/node_modules/bluebird/js/main/util.js:64:19)
    at Promise$_callHandler [as _callHandler] (/opt/NYUAMS/node/ebs/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:708:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/opt/NYUAMS/node/ebs/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:724:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/opt/NYUAMS/node/ebs/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:896:14)
    at Promise$_fulfillPromises [as _fulfillPromises] (/opt/NYUAMS/node/ebs/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:1041:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/opt/NYUAMS/node/ebs/node_modules/sequelize/node_modules/bluebird/js/main/async.js:64:12)
    at Async$consumeFunctionBuffer (/opt/NYUAMS/node/ebs/node_modules/sequelize/node_modules/bluebird/js/main/async.js:37:14)
    at Promise$_Scheduler (/opt/NYUAMS/node/ebs/node_modules/sequelize/node_modules/bluebird/js/main/schedule.js:40:58)
    at process._tickDomainCallback (node.js:463:13)

**Comment by leobardoramon** [comment]
Side question:

Would this be a good opportunity to remove the Thumbnail generation feature?

**Comment by gosha1128** [comment]
Sure.  Add that to the list...

-g

**Comment by gosha1128** [comment]
OK, so I had to do the following at the EBS:

root@ip-10-0-3-248:/opt/NYUAMS/node/ebs# rm -fr /amsfiles/EBSFILES/FILES/1260
root@ip-10-0-3-248:/opt/NYUAMS/node/ebs# rm -fr /amsfiles/EBSFILES/FILES/1261
root@ip-10-0-3-248:/opt/NYUAMS/node/ebs# rm -fr /amsfiles/EBSFILES/FILES/1262
root@ip-10-0-3-248:/opt/NYUAMS/node/ebs# rm -fr /amsfiles/EBSFILES/FILES/1263
root@ip-10-0-3-248:/opt/NYUAMS/node/ebs# rm -fr /amsfiles/EBSFILES/FILES/1264
root@ip-10-0-3-248:/opt/NYUAMS/node/ebs# rm -fr /amsfiles/EBSFILES/FILES/1265
root@ip-10-0-3-248:/opt/NYUAMS/node/ebs# rm -fr /amsfiles/EBSFILES/FILES/1266
root@ip-10-0-3-248:/opt/NYUAMS/node/ebs# rm -fr /amsfiles/EBSFILES/FILES/1267
root@ip-10-0-3-248:/opt/NYUAMS/node/ebs# rm -fr /amsfiles/EBSFILES/FILES/1268
root@ip-10-0-3-248:/opt/NYUAMS/node/ebs# rm -fr /amsfiles/EBSFILES/FILES/1269


Here is why:

SQL thinks that the last file has an ID of 1259.

When you upload a file, SQL says to use an ID of 1260 ( = 1259 + 1 ).

But, when EBS tries to create the directory container for that file, it already exists.

In fact, not only did 1260 exist, but also 1260-1269.

This just means that the SQL database you restored from is out-of-sync with the file system you restored from.  From the look of it...the file system is ahead of the SQL.

Since its DEV, it doesn't matter and I just deleted all those file ID directories.

Does that make sense ?

---

This is a big deal when it happens in production, and your restore of SQL is out of sync with the file system.  That is why you must take SQL backups and file backups at the same time.

**Comment by leobardoramon** [comment]
This does not make sense to me...

The File Server Image , RDS Snapshot , Volume were all created at the same time...

The only thing that was created at a later date was the Server Image ( which I was told would not affect the fileserver data... )

So I'm still not clear on how this happened or how to avoid it from happening in the future.

Any thoughts?

**Comment by leobardoramon** [comment]
Either way, if there is a deeper problems, I'm sure it will resurface.

Shall I move forward and continue testing?

**Comment by gosha1128** [comment]
Yes proceed testing..this will happen unfortunately...now you know what to
look for !

**Comment by leobardoramon** [comment]
Good.

Closing

**Comment by leobardoramon** [comment]
Still happening

**Comment by gosha1128** [comment]
Go through the delete process and let me know if it fixes it.

**Comment by leobardoramon** [comment]
the directory /amsfiles/EBSFILES/FILES/ contains directories from up to "/2012"...

What's the appropriate solutions?  Remove directories 1279-2012?

Can we just have SQL start from "2013"?

**Comment by gosha1128** [comment]
No, SQL takes the last valid file ID and adds 1.

-g

**Comment by leobardoramon** [comment]
So what would the command line be to remove directories 1279-2012?

- >cd /amsfiles/EBSFILES/FILES/
- >rm -fr {1279..2012}

?

**Comment by gosha1128** [comment]
Just do them 1 at a time :(

**Comment by leobardoramon** [comment]
George!  That's 741 directories...

**Comment by gosha1128** [comment]
That is crazy how out of sync SQL is to this FILE system !

OK, but you have to be very careful...

rm -fr  .../{1279..2012}

Should work.

But, test it on a smaller subset, like:

rm -fr .../{1279...1281}

That should delete 3 files.

http://superuser.com/questions/138282/how-to-delete-files-on-the-command-line-with-regular-expressions

**Comment by leobardoramon** [comment]
Before I do that, check this out:

<img width="1178" alt="screen shot 2016-06-23 at 5 41 51 pm" src="https://cloud.githubusercontent.com/assets/2165796/16321282/14b73b68-396a-11e6-8654-560f3493681a.png">

**Comment by gosha1128** [comment]
OK, you should also go to the SQL prompt and investigate the file table,
like this:

sql>>  SELECT COUNT(*) FROM Files

That will give you the total count of files from SQL's perspective

**Comment by leobardoramon** [comment]
I need a command line for accessing sql via DEV server...

PROD:

- >mysql -h ebs.cdsq90t3hkch.us-east-1.rds.amazonaws.com -u ebs -p

would this be correct:

- >mysql -h dev3.cdsq90t3hkch.us-east-1.rds.amazonaws.com -u dev3 -p

**Comment by gosha1128** [comment]
Yes, use the connection string thats in config.js.

MAKE SURE ITS DEV !!!

-g

**Comment by leobardoramon** [comment]
it looks like a something might need to change , either the content of "config.js" or the connections string

- See how Amazon Web Service DB Instance name is "dev3" ( whereas the PROD instance name is "ebs" )

- And in the config.js file , 'ebs' appears twice

- Was this supposed to have been changed in config.js from 'ebs' to 'dev3' ?

<img width="503" alt="screen shot 2016-06-23 at 6 14 23 pm" src="https://cloud.githubusercontent.com/assets/2165796/16322200/7d26e2de-396f-11e6-845a-086889a75e6d.png">
<img width="1447" alt="screen shot 2016-06-23 at 6 19 33 pm" src="https://cloud.githubusercontent.com/assets/2165796/16322199/7d268410-396f-11e6-9ab7-7ef3401cc553.png">

**Comment by gosha1128** [comment]
Yes we need to make sure you are not affecting production SQL and FILEPROD.

List here the :

1) SQL connection string for DEV EBS and

2) How DEV EBS mounts PRODFILES in /etc/fsab

**Comment by leobardoramon** [comment]
1) I don't know, I was cutting and pasting from the SQL connection string for PROD:

<img width="771" alt="screen shot 2016-06-23 at 7 02 35 pm" src="https://cloud.githubusercontent.com/assets/2165796/16322967/156b2262-3975-11e6-9bbe-a135b080fb1a.png">

2) How DEV EBS mounts to "DEVFILES":

<img width="566" alt="screen shot 2016-06-23 at 7 04 15 pm" src="https://cloud.githubusercontent.com/assets/2165796/16322992/54f85fb2-3975-11e6-8ca4-58ec7d432fb9.png">

it looks like there's a line missing...

**Comment by gosha1128** [comment]
OK, do the following:

Login to a DEV EBS system:

1)  what is the sql connect string in config.js

2)  what is the output of the command:

>> df

Login to a PROD EBS system:

1)  what is the sql connect string in config.js

2)  what is the output of the command:

>> df

This is all we need to make sure we aren't confusing systems.

**Comment by leobardoramon** [comment]
1) config.js

<img width="634" alt="screen shot 2016-06-24 at 10 39 39 am" src="https://cloud.githubusercontent.com/assets/2165796/16341010/fdcd687a-39f8-11e6-8d98-3d9eb6f4ab7f.png">

2) >df

<img width="632" alt="screen shot 2016-06-24 at 10 38 02 am" src="https://cloud.githubusercontent.com/assets/2165796/16341015/05114b88-39f9-11e6-8c0e-ff26fbd1ef61.png">

**Comment by gosha1128** [comment]
OK, thats the problem !

Notice that both the EBS DEV and PROD are pointing to the same machine for
PRODFILES:

10.0.0.182:/amsfiles

If that is PRODFILES, then we deleted files from PRODFILES.  oops !

1) It should be ok, but you will need restore those deleted file
directories from a backup of PRODFILES.  Do you have a list of file
directories we deleted ?  ( Fortunately, nothing in SQL was affected by
anything we did :)

2) Eventually, we should use firewall rules to make sure DEV and PROD
machines can't possibly even talk to each other...

-g

**Comment by leobardoramon** [comment]
1)  Directories affected:  1260..1269

Q:  What are the steps to change the direction of DEV Volume?

**Comment by gosha1128** [comment]
Don't worry about pointing DEV for the moment.

You need to restore those files from a backup, unfortunately.

**Comment by leobardoramon** [comment]
Okay, what is the best way to do that?

should I google?

**Comment by gosha1128** [comment]
Because its so few files...the best thing to do is NOT a full restore.

Just bring up a reasonably recent backup to a new volume.  Then copy the
affected directories over.

Lets worry about setting this up so it doesn't happy in the future, after
the restore.

-g

**Comment by leobardoramon** [comment]
I left this Volume sitting to attach for 2 hours and it still has a spinning wheel...What do I do?

<img width="1332" alt="screen shot 2016-06-24 at 2 23 22 pm" src="https://cloud.githubusercontent.com/assets/2165796/16346968/20d1c5b8-3a18-11e6-8c2b-8ff699ac7c42.png">

**Comment by gosha1128** [comment]
google around...but i am guessing because its such a large volume then
you'll just have to wait... :(

also, you can open a tech support issue with amazon and tell them whats up.

**Comment by leobardoramon** [comment]
<img width="999" alt="screen shot 2016-06-24 at 2 42 16 pm" src="https://cloud.githubusercontent.com/assets/2165796/16347301/f0a9bc18-3a19-11e6-8e71-6c262edbf66a.png">
<img width="815" alt="screen shot 2016-06-24 at 2 42 39 pm" src="https://cloud.githubusercontent.com/assets/2165796/16347300/f0a6a6b8-3a19-11e6-96e3-142386ca4cbf.png">

**Comment by leobardoramon** [comment]
I want to run a filesystem check on the volume that I ran "Force Detach Volume" via AWS console.

On the DEVFILES system ( 54.173.116.170 ) , I tried running the command:

 ->fsck /dev/xvdf

and I got this:
<img width="694" alt="screen shot 2016-07-05 at 1 03 01 pm" src="https://cloud.githubusercontent.com/assets/2165796/16592902/dafe5e56-42b0-11e6-9c4d-270a0bc31e07.png">

I'm a little confused because I'm trying to check on the volume that is mounted.  Any suggestions?

**Comment by gosha1128** [comment]
Right.

I assume that you are sure its a DEV system.  Just checking...

OK, so look at this page.  It says you should do fsck on an unmounted
volume.

https://help.ubuntu.com/community/FilesystemTroubleshooting

**Comment by leobardoramon** [comment]
Cool.

The fsck command gave a "clean" transcripts, so I've mounted the volume and we should be good.

<img width="717" alt="screen shot 2016-07-05 at 5 40 03 pm" src="https://cloud.githubusercontent.com/assets/2165796/16600932/ad3478bc-42d7-11e6-8f78-bdc81bbbd46b.png">

**Comment by gosha1128** [comment]
Very good.  Make sure to discuss with AMS the proper firewall rules to
ensure DEV and PROD systems cannot see each other !

**Comment by leobardoramon** [comment]
------Steps/suggestions to make sure DEV and PROD aren't ever confused

 - Put DEV and PROD each in their own VPC ( not sure what the cost is here, i think its free )

 - Separate FireWall Rules for DEV and PROD machines ( i.e., only DEVEBS machines can talk to DEVPROD, only PRODEBS can see PRODFILES ).  This would have prevented, for example, DEVEBS from mounting PRODFILES ( that was the issue we had )

 - Making sure that only DEVEBS can talk to DEVSQL and PRODEBS can talk to PRODSQL  ( I believe you can set this up in RDS, not sure )

 - Separating DEV and PROD machines in the Amazon Console, and possibly separate logins ( not sure if this is possible )

 - #569  Making it obvious at the Web EBS App that you are logging into a DEV system vs a PROD system.  Maybe different background color or something on the web pages.

**Comment by leobardoramon** [comment]
Also, can you please help me format the new line in the /etc/fstab files, please?

See AWS Instructions:

<img width="911" alt="screen shot 2016-07-05 at 6 10 23 pm" src="https://cloud.githubusercontent.com/assets/2165796/16601682/3f279cd2-42dc-11e6-9262-4f10ec6d258c.png">

**Comment by gosha1128** [comment]
Right, so on the command line you would mount like this--

sudo mount 1.2.3.4:/amsfiles /amsfiles

**Comment by gosha1128** [comment]
...and the /etc/fstab entry would look somewhat similar:

Looks at this page and search for the text "fstab"--

https://www.digitalocean.com/community/tutorials/how-to-set-up-an-nfs-mount-on-ubuntu-14-04

**Comment by leobardoramon** [comment]
Issue Resolved.

Closing.
