### ISSUE TITLE
DEV - Test Case:  Orders>New Order Wiz>Panel 3 ( file uploader ) - uploaded same multiple times

### ISSUE THREAD

**Issue by leobardoramon** [gosha1128/NYUAMS#581]
When uploading a file, the system got stuck after "100%" and started uploading all over

Uploader Stuck at 100%

The 3rd file uploaded 3 times and the server crashed the 4th time

# Terminal

## Start Server

- Open a Terminal window
- "cd" into your PROD1.pem directory
- >ssh -i PROD1.pem ubuntu@54.165.240.163
- >sudo forever stopall
- >sudo bash
- >cd /opt/NYUAMS/node/ebs
- >node app.js nfs

## Start Fileproxy Server

- Open a new Terminal window/tab
- cd into your "fileproxy dir"/NYUAMS/node/ebs/local
- >sudo killall node
- >sudo node fileproxy.js

# Chrome

- Launch Chrome
- In Address Bar, type server address: "54.165.240.163"
- Login , "leo"
- Password , "l6shooter"
- Domain , "Local"
- "Sign In"
- Create New Order
- Project Name:  "Test Project ( 5/19 Crash )"
- Service:  Wide Format
- File Upload
>"Dark Matter_2016_Eight_a.tif" ( 1.9 GB )
>"Dark Matter_2016_Ten_a.tif" ( 1.9 GB )
>"Dark Matter_2016_ Six_a.tif" ( 1.2 GB )

# Notes

- download zip: https://drive.google.com/open?id=0B_9JEK6SVk1bODBPVlhVa1dMeGs
- See entire terminal transcript here:
https://drive.google.com/open?id=1AtHkhql0SvT-yO9W5q2GUy-o6aTBnAyUbQLqjw9QV2k

**Comment by gosha1128** [comment]
I bet you forgot to clear cache

**Comment by leobardoramon** [comment]
yes i did...

**Comment by leobardoramon** [comment]
*yes I did forget...

**Comment by leobardoramon** [comment]
"file already exist" error is happening again:

GET /events?sessionid=1989&all=true 200 0.451 ms - -
GET /events?sessionid=1989&all=true 200 0.557 ms - -
GET /events?sessionid=1989&all=true 200 0.383 ms - -
GET /events?sessionid=1989&all=true 200 0.786 ms - -
GET /events?sessionid=1989&all=true 200 3.136 ms - -
GET /events?sessionid=1989&all=true 200 1.835 ms - -
CF args 301 undefined undefined
ABOUT TO CREATE undefined undefined
CCFF undefined undefined
WARNING: upload: cmd-> identify "/tmp/12855-1otkc8s.tif"
WARNING: execS: { code: 1,
  stdout: '/tmp/12855-1otkc8s.tif TIFF 24534x25920 24534x25920+0+0 8-bit DirectClass 1.203GB 0.000u 0:00.679\nidentify.im6: Incompatible type for "RichTIFFIPTC"; tag ignored. `TIFFFetchNormalTag\' @ warning/tiff.c/TIFFWarnings/768.\nidentify.im6: Bogus "StripByteCounts" field, ignoring and calculating from imagelength. `TIFFReadDirectory\' @ warning/tiff.c/TIFFWarnings/768.\nidentify.im6: /tmp/12855-1otkc8s.tif: Can not read TIFF directory count. `TIFFFetchDirectory\' @ error/tiff.c/TIFFErrors/508.\nidentify.im6: Failed to read custom directory at offset 1907819100. `TIFFReadCustomDirectory\' @ error/tiff.c/TIFFErrors/508.\n' }
GET /events?sessionid=1989&all=true 200 0.373 ms - -
GET /events?sessionid=1989&all=true 200 0.275 ms - -
Executing (default): INSERT INTO `Files` (`url`,`fmt`,`status`,`deviceid`,`width`,`height`,`asset`,`des`,`name`,`pjp`,`fspath`,`fsdir`,`createdAt`,`updatedAt`) VALUES (NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2016-06-23 19:57:45','2016-06-23 19:57:45');
INFO: sql: SQL new ok.
WARNING: db_file: fdir= /amsfiles/EBSFILES/FILES/1271

/opt/NYUAMS/node/ebs/node_modules/sequelize/node_modules/bluebird/js/main/async.js:79
            throw res.e;
                     ^
Error: EEXIST, file already exists '/amsfiles/EBSFILES/FILES/1271'
    at Object.fs.mkdirSync (fs.js:642:18)
    at /opt/NYUAMS/node/ebs/db/file.js:372:8
    at tryCatch1 (/opt/NYUAMS/node/ebs/node_modules/sequelize/node_modules/bluebird/js/main/util.js:64:19)
    at Promise$_callHandler [as _callHandler] (/opt/NYUAMS/node/ebs/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:708:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/opt/NYUAMS/node/ebs/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:724:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/opt/NYUAMS/node/ebs/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:896:14)
    at Promise$_fulfillPromises [as _fulfillPromises] (/opt/NYUAMS/node/ebs/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:1041:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/opt/NYUAMS/node/ebs/node_modules/sequelize/node_modules/bluebird/js/main/async.js:64:12)
    at Async$consumeFunctionBuffer (/opt/NYUAMS/node/ebs/node_modules/sequelize/node_modules/bluebird/js/main/async.js:37:14)
    at Promise$_Scheduler (/opt/NYUAMS/node/ebs/node_modules/sequelize/node_modules/bluebird/js/main/schedule.js:40:58)
    at process._tickDomainCallback (node.js:463:13)
root@ip-10-0-3-248:/opt/NYUAMS/node/ebs#

**Comment by gosha1128** [comment]
Yes - you should file 'need to obsessively clear the cache between builds
and dev/prod' as a minor bug.

It can be addressed with non-trivial effort.

**Comment by gosha1128** [comment]
I can't repro this on DEV right now, can you ?

**Comment by leobardoramon** [comment]
no.  Closing for now.
