### ISSUE TITLE
DEV server - 54.165.240.163 - cannot run server

### ISSUE THREAD

**Issue by leobardoramon** [gosha1128/NYUAMS#582]
I get an error when I try to start the server

 ->ssh -i PROD1.pem ubuntu@54.165.240.163
 ->sudo forever stopall
 ->sudo bash
 ->cd /opt/NYUAMS/node/ebs
 ->node app.js nfs

<img width="718" alt="screen shot 2016-07-05 at 5 58 03 pm" src="https://cloud.githubusercontent.com/assets/2165796/16601356/11d69848-42da-11e6-9c58-828903f7aa3c.png">

**Comment by leobardoramon** [comment]
I think it may have something to do with this step in the instructions you gave me that I'm having trouble figuring out:

<img width="394" alt="screen shot 2016-07-05 at 6 00 15 pm" src="https://cloud.githubusercontent.com/assets/2165796/16601449/8fba9e6c-42da-11e6-9ef4-3f7f0161cc42.png">

see DEVFILES info via AWS Console:

<img width="1377" alt="screen shot 2016-07-05 at 6 01 01 pm" src="https://cloud.githubusercontent.com/assets/2165796/16601465/9f40c71c-42da-11e6-9b70-b9a0af247260.png">

**Comment by gosha1128** [comment]
Yes, remember when you mount a directory like this you need a few things:

1)  You need to login to the machine (DEVFILES) that is mounting the
DEVVOLUME and you need to make sure the volume is properly mounted at
/amsfiles.  ( the command df will help you here ).

2)  on DEV FILES, you need to make sure the exports file is accepting
connections from the ip address(s) of DEV EBS.

3)  If you made any modifications to exports (#2 above) then you must
restart NFS.

4)  on DEV EBS, you should now be able to mount the shared drive via the
"mount" command.  You would use the ip address of DEV FILES.

Does that all make sense ?

**Comment by leobardoramon** [comment]
The mounting worked:

<img width="578" alt="screen shot 2016-07-06 at 1 56 14 pm" src="https://cloud.githubusercontent.com/assets/2165796/16628914/ac3b07aa-4381-11e6-9c14-83896cca3fcc.png">

I'm getting an invalid login message from chrome when I try to log in, and this is the Terminal transcript:

POST /uploads?sessionid=login&login=leo&domain=local - - ms - -
@@@@@UPLOAD
PARSED URL { protocol: null,
  slashes: null,
  auth: null,
  host: null,
  port: null,
  hostname: null,
  hash: null,
  search: '?sessionid=login&login=leo&domain=local',
  query: { sessionid: 'login', login: 'leo', domain: 'local' },
  pathname: '/uploads',
  path: '/uploads?sessionid=login&login=leo&domain=local',
  href: '/uploads?sessionid=login&login=leo&domain=local' }
PARSED URL KEY login
BPARSED URL { protocol: null,
  slashes: null,
  auth: null,
  host: null,
  port: null,
  hostname: null,
  hash: null,
  search: '?sessionid=login&login=leo&domain=local',
  query: { sessionid: 'login', login: 'leo', domain: 'local' },
  pathname: '/uploads',
  path: '/uploads?sessionid=login&login=leo&domain=local',
  href: '/uploads?sessionid=login&login=leo&domain=local' } Object {}
CPARSED URL { protocol: null,
  slashes: null,
  auth: null,
  host: null,
  port: null,
  hostname: null,
  hash: null,
  search: '?sessionid=login&login=leo&domain=local',
  query: { sessionid: 'login', login: 'leo', domain: 'local' },
  pathname: '/uploads',
  path: '/uploads?sessionid=login&login=leo&domain=local',
  href: '/uploads?sessionid=login&login=leo&domain=local' }
AAAA
BBB
CCC
DDDD
WARNING: session: login attempt...
Executing (default): SELECT * FROM `users`;
Executing (default): SELECT * FROM `users` WHERE `users`.`userid`=1;
Executing (default): SELECT * FROM `users` WHERE `users`.`userid`=2;
Executing (default): SELECT * FROM `users` WHERE `users`.`userid`=3;
Executing (default): SELECT * FROM `users` WHERE `users`.`userid`=4;
Executing (default): SELECT * FROM `users` WHERE `users`.`userid`=5;
Executing (default): SELECT * FROM `users` WHERE `users`.`userid`=6;
Executing (default): SELECT * FROM `users` WHERE `users`.`userid`=7;
Executing (default): SELECT * FROM `users` WHERE `users`.`userid`=8;
Executing (default): SELECT * FROM `users` WHERE `users`.`userid`=9;
Executing (default): SELECT * FROM `users` WHERE `users`.`userid`=10;
Executing (default): SELECT * FROM `users` WHERE `users`.`userid`=11;
Executing (default): SELECT * FROM `users` WHERE `users`.`userid`=12;
Executing (default): SELECT * FROM `users` WHERE `users`.`userid`=13;
Executing (default): SELECT * FROM `users` WHERE `users`.`userid`=14;
password feb26c7bb69173e64991e2757f0058a1 feb26c7bb69173e64991e2757f0058a1
POST /uploads?sessionid=login&login=leo&domain=local - - ms - -

**Comment by gosha1128** [comment]
The user / password information is stored in SQL.

So look at your SQL connection string and login to that instance of sql (
using the "mysql" command at terminal - do you remember how to do that ? )

At the mysql prompt, type...

mysql> use ebs
mysql> select * from users

That will list all the accounts and the password hashes.

if your password hash does not match, then change the password hash using
previous instructions on this.

**Comment by leobardoramon** [comment]
This is what I'm seeing for login data in mysql:

<img width="585" alt="screen shot 2016-07-06 at 6 20 37 pm" src="https://cloud.githubusercontent.com/assets/2165796/16636563/e503d100-43a6-11e6-9079-7628c7002371.png">

http://www.miraclesalad.com/webtools/md5.php verfies that my password translates to:
feb26c7bb69173e64991e2757f0058a1

in other words...the login credentials that I'm using are correct.

You should also know that when I click the "Login" button, the server side spends about 60-75 seconds working and terminal looks like this:

<img width="583" alt="screen shot 2016-07-06 at 6 30 35 pm" src="https://cloud.githubusercontent.com/assets/2165796/16636707/d48b26e2-43a7-11e6-98eb-670775bcb0ec.png">

- with a pulsing cursor on the bottom-left corner

**Comment by gosha1128** [comment]
OK, give me the login information for DEVEBS...is there a new PEM key ?

**Comment by leobardoramon** [comment]
same pem key

 ->ssh -i PROD1.pem ubuntu@54.165.240.163

MYSQL

 .>mysql -h dev3.cdsq90t3hkch.us-east-1.rds.amazonaws.com -u ebs -p

**Comment by leobardoramon** [comment]
I haven't done this yet:

<img width="766" alt="screen shot 2016-07-06 at 6 47 32 pm" src="https://cloud.githubusercontent.com/assets/2165796/16637085/6f30a436-43aa-11e6-928b-b6e8575fac21.png">

- I'm not sure what each command means, so I don't know which one applies - could this be why it's not working?

**Comment by gosha1128** [comment]
Thats fine.  You manually mounted and thats ok for now.

The fstab thing is so that if it ever reboots, it automatically does what
you did manually.

**Comment by gosha1128** [comment]
OK, it looks like you've done everything right, so I'll have to check it
out....

**Comment by leobardoramon** [comment]
K.  I'll keep out for now.  Let me know what you find out.

**Comment by gosha1128** [comment]
Oh wait...I think I see...

It looks like i can't create a file under the exported directory on DEVEBS.

It may have been mounted read-only, or the exports file won't allow writes.

Do you recall the mount command on DEVEBS ?

-g

**Comment by leobardoramon** [comment]
I used the private IP:
 ->sudo mount 10.0.2.51:/amsfiles /amsfiles

I used the private IP of DEVFILES because PROD used the private IP of PRODFILES

**Comment by gosha1128** [comment]
OK, how about we kill a few birds with one stone :)

1)  go to DEVEBS, sudo bash

2)  open and edit the file /etc/fstab

3)  notice the entry/row which is defining the local mount directory as
/amsfiles (second column).  Notice for that row, the first column - it is
trying to mount from a machine at 10.0.0.182.

that's not likely correct, so fix it to the address it should be using.

once you've made changes, save the file.

4)  type "df" at the command line.  notice the /amsfiles mount.  Is it
using the right address ?  if not, and you properly changed the entry in
/etc/fstab, then you need to unmount it and remount it.  Do that as follows:

>> umount /amsfiles
>> mount /amsfiles
>> df

The last command is to confirm all of the mounts.  Is it right ?

---

As a final test, you should go into /amsfiles on DEVEBS and create a file.
The following will do this:

>> cd /amsfiles
>> touch testfile
>> ls
>> rm testfile

**Comment by leobardoramon** [comment]
Okay, all of these steps were important and needed:
1) change file "/etc/fstab"

<img width="580" alt="screen shot 2016-07-06 at 7 20 31 pm" src="https://cloud.githubusercontent.com/assets/2165796/16637831/f9609544-43af-11e6-8faf-049c85a61b3d.png">

2) umount , mount , create testfile , remove testfile

<img width="667" alt="screen shot 2016-07-06 at 7 25 19 pm" src="https://cloud.githubusercontent.com/assets/2165796/16637844/187bf16c-43b0-11e6-96a6-caa2d92ba780.png">

**Comment by gosha1128** [comment]
Ok now try DEVBS login

**Comment by leobardoramon** [comment]
wow!  You're magic.  It worked.  Everything looks in order.

 - file successfully uploaded to DEVFILES ( img1 , img2 )
 - file upload verified via Terminal application ( img3 )

<img width="1433" alt="screen shot 2016-07-06 at 7 50 38 pm" src="https://cloud.githubusercontent.com/assets/2165796/16638333/683fffd2-43b4-11e6-9ade-d8988fb8661e.png">
<img width="523" alt="screen shot 2016-07-06 at 7 50 30 pm" src="https://cloud.githubusercontent.com/assets/2165796/16638334/68464360-43b4-11e6-8b61-ce8a574c01df.png">

<img width="685" alt="screen shot 2016-07-06 at 7 50 20 pm" src="https://cloud.githubusercontent.com/assets/2165796/16638346/8040817e-43b4-11e6-97ff-af3c673387c8.png">

**Comment by gosha1128** [comment]
Great.  snapshot everything with todays date and time:

DEVSQL
DEVFILES
DEVVOLUME
DEVEBS

**Comment by leobardoramon** [comment]
We have snapshots:

 - DEVSQL

<img width="1440" alt="screen shot 2016-07-06 at 8 32 38 pm" src="https://cloud.githubusercontent.com/assets/2165796/16639285/0cb12c7e-43bc-11e6-9a91-b18e7609907e.png">

 - DEVFILES
 - DEVEBS
 - DEVFILES Volume

<img width="1440" alt="screen shot 2016-07-06 at 8 51 03 pm" src="https://cloud.githubusercontent.com/assets/2165796/16639286/0cb226ec-43bc-11e6-8500-1ecabd38e5ef.png">

 - DEVFILES AMI
 - DEVEBS AMI

<img width="1440" alt="screen shot 2016-07-06 at 8 53 57 pm" src="https://cloud.githubusercontent.com/assets/2165796/16639284/0cb1064a-43bc-11e6-82d1-ae980cbb5cf9.png">

Tags:
Name   ,   yyyy-m-d-hh-mm
Description , everything points to dev, file successfully uploaded ; FYI, git branch, 'maintenance1'

**Comment by leobardoramon** [comment]
Issue Resolved.

Closing
