### ISSUE TITLE
DEV - Dedicated VPC

### ISSUE THREAD

**Issue by leobardoramon** [gosha1128/NYUAMS#583]
Due to cross-communication issues that have recently occurred between DEV & PROD SQL servers, we will be launching a VPC that is dedicated to DEV, this way communication will not occur outside of each respective VPC.

**Comment by leobardoramon** [comment]
George,

Should I just copy the CIDR Block setting from the PROD VPC?

**Comment by gosha1128** [comment]
What is PRODs CIDR block ?

**Comment by leobardoramon** [comment]
10.0.0.0/16

**Comment by gosha1128** [comment]
You should choose something different for dev vpc - that way you have an
additional way to differentiate dev and prod by their private ip
addresses...

-g

**Comment by leobardoramon** [comment]
I used 192.168.0.0/16

<img width="1435" alt="screen shot 2016-07-10 at 10 10 48 pm" src="https://cloud.githubusercontent.com/assets/2165796/16718178/89dd72e8-46eb-11e6-97f4-b006ac021bdc.png">

**Comment by gosha1128** [comment]
Nice work.  That's the most common private address range.  The other one is
10.0.X.X.

-g

**Comment by leobardoramon** [comment]
In which VPC should the DEVSQL Instance go?

 - default VPC ( vpc-a9e59ecc ) , PRODUCTION VPC ( vpc-30070255 ) , DEVELOPMENT VPC ( vpc-0bdc516c )

 - PRODSQL is in the default VPC ( vpc-a9e59ecc aka not PRODUCTION VPC )

 - current DEVSQL is in the default VPC also ( vpc-a9e59ecc )

**Comment by gosha1128** [comment]
ALL DEV STUFF SHOULD GO INTO DEV-VPC.

DEV-VPC AND PROD-VPC should share nothing !!! :)

-g

**Comment by leobardoramon** [comment]
I have 

 - DEVSQL ( devsql.cdsq90t3hkch.us-east-1.rds.amazonaws.com )
 - DEVEBS ( 52.91.247.124 )
 - DEVFILES ( 54.210.91.200 )

all up and running...however, I'm not able to connect to the server via ssh like I normally do...the connection is timing out

<img width="586" alt="screen shot 2016-07-17 at 6 08 29 pm" src="https://cloud.githubusercontent.com/assets/2165796/16904373/86d2f5c4-4c49-11e6-8c5c-63d47f392d80.png">

**Comment by gosha1128** [comment]
OK, so a VPC is essentially a firewall.

You need to open up the firewall for this kind of connection.

Have you been through this VPC exercise ?

http://docs.aws.amazon.com/AmazonVPC/latest/GettingStartedGuide/ExerciseOverview.html

**Comment by leobardoramon** [comment]
Thank you.

I'm having trouble mounting DEVFILES ( 54.210.91.200 ) to DEVEBS ( 52.91.247.124 )

<img width="595" alt="screen shot 2016-07-18 at 3 39 05 am" src="https://cloud.githubusercontent.com/assets/2165796/16912527/801fa8da-4c99-11e6-98c0-4875f18c83ad.png">

**Comment by gosha1128** [comment]
OK, one thing you can do is make sure that the machine you are ssh'ed into
can reach the other machine:

>> ping 192.168.3.107

What does that say ?

**Comment by leobardoramon** [comment]
It's been stuck here for about 15 minutes ( with the cursor at the bottom left corner )

<img width="626" alt="screen shot 2016-07-18 at 9 16 16 am" src="https://cloud.githubusercontent.com/assets/2165796/16922045/eb6f517e-4cc8-11e6-8cfc-4d4dc9be7fc0.png">

**Comment by gosha1128** [comment]
Great...it means the machines can't talk to each other at all...are you
sure they are in the same vpc ?

**Comment by gosha1128** [comment]
Great...it means the machines can't talk to each other at all...they are in
the same vpc ?

**Comment by leobardoramon** [comment]
Yes they are

<img width="1424" alt="screen shot 2016-07-18 at 9 55 24 am" src="https://cloud.githubusercontent.com/assets/2165796/16923252/22c5e516-4cce-11e6-8b66-b9470b2c76a9.png">
<img width="1435" alt="screen shot 2016-07-18 at 9 55 43 am" src="https://cloud.githubusercontent.com/assets/2165796/16923251/22c561c2-4cce-11e6-93f9-f9cb3ccb66f8.png">

**Comment by gosha1128** [comment]
This post seems relevant:

https://forums.aws.amazon.com/thread.jspa?threadID=90972

"You could try adding a rule in each security group for "All traffic" with
0.0.0.0/0 as the source. The security group is a whitelist, which means
anything not listed there will be blocked. Your instances won't even be
allowed to communicate with each other internally unless you say so. "

**Comment by leobardoramon** [comment]
Cool, it worked

<img width="619" alt="screen shot 2016-07-18 at 11 10 29 am" src="https://cloud.githubusercontent.com/assets/2165796/16925281/520c0c06-4cd8-11e6-8846-0543ca0bfd1f.png">

**Comment by gosha1128** [comment]
Yes, but also make sure only DEV VPC machines can reach each other.

For example, log into a PROD EBS and try to ping that machine...

-g

**Comment by leobardoramon** [comment]
Okay, so:

 - DEVEBS ONLY talks to DEVFILES
 - DEVFILES ONLY talks to DEVEBS

 - PROD4 , PROD5 , PRODFILES are little different, but we will not touch those for now

**Comment by gosha1128** [comment]
Great - nice work.  Basically i want to make sure the VPC is doing what we
want - any DEV machines cannot reach any PROD machine via the private ip
addresses.

Woo hoo !

**Comment by leobardoramon** [comment]
Nice!

I'm having trouble running a command from DEVEBS ( 52.91.247.124 ):
 ->mount 192.168.3.107:/amsfiles /amsfiles

<img width="614" alt="screen shot 2016-07-18 at 12 48 32 pm" src="https://cloud.githubusercontent.com/assets/2165796/16928310/dbdd0db4-4ce6-11e6-82b0-053089a7cef5.png">

**Comment by gosha1128** [comment]
OK, cool.

So if you are sure you can "see" the other machine via "ping", then the
next things to check are:

1) since you are trying to mount another machines "nfs export", make sure
the other machine is indeed export that directory.

a) is DEV FILES exporting the directory /amsfiles ?  is the nfs started on
that machine ?  whats in the exports file ?

b) remember, in the exports file mentions what machines can connect to the
exported directory.  does that look right ?

c)  remember to restart nfs on the machine exporting the directory - if you
change anything

**Comment by leobardoramon** [comment]
It worked!  

<img width="612" alt="screen shot 2016-07-18 at 1 05 06 pm" src="https://cloud.githubusercontent.com/assets/2165796/16928696/e15f9df4-4ce8-11e6-9bed-a28cc868c9ba.png">

It DID have to do with the "exports" file ; the VPC's CIDR Block needed to be updated

<img width="621" alt="screen shot 2016-07-18 at 1 06 02 pm" src="https://cloud.githubusercontent.com/assets/2165796/16928705/e9c2c4ee-4ce8-11e6-87dd-736bebe07c62.png">

**Comment by leobardoramon** [comment]
I just tried to run DEVEBS and got an error

<img width="679" alt="screen shot 2016-07-18 at 1 12 57 pm" src="https://cloud.githubusercontent.com/assets/2165796/16928855/c2db3504-4ce9-11e6-8f07-140acde74f8a.png">

**Comment by gosha1128** [comment]
Great.

Its having trouble connecting to SQL.

So this is another place we have to be careful and we should take advantage
of VPC.

Make sure the SQL connection string points to the DEV RDS instance.

If it is...then I believe you also need to make sure that the DEV RDS
instance is allowing connections from DEV machines.  I forget how to do
that...maybe its one at the RDS console.

**Comment by leobardoramon** [comment]
Okay, so I added the "Whitelist" rule ( All Traffic , 0.0.0.0/0 ) to the RDS Instance Security Group and that fixed the problem.

DEVEBS works, file uploaded successfully , smoketest PASSED !! <3

<img width="1428" alt="screen shot 2016-07-18 at 1 31 13 pm" src="https://cloud.githubusercontent.com/assets/2165796/16929322/15e414b2-4cec-11e6-80ed-ff2f5c26b59a.png">

**Comment by gosha1128** [comment]
Ok do me a favor...change the SQL connection string to PROD RDS and make
sure it fails when you start DEV EBS

**Comment by leobardoramon** [comment]
it FAILED...in a good way :)

<img width="671" alt="screen shot 2016-07-18 at 1 45 50 pm" src="https://cloud.githubusercontent.com/assets/2165796/16929838/53192d52-4cee-11e6-96e2-c9f1ab9ad8f6.png">

**Comment by gosha1128** [comment]
Great work...VPC works ! Now send me list of what you want done in
order...easy stuff first

**Comment by leobardoramon** [comment]
Great.  This issue is resolved. Closing.
