### ISSUE TITLE
DEV server - 54.227.100.240 - unable to run server

### ISSUE THREAD

**Issue by leobardoramon** [gosha1128/NYUAMS#584]
Now that I've restarted the DEVEBS and DEVFILES instances, they have new Public IPs.

I've added DEVEBS IP to:

 - AWS>DEVFILES>Security Group>Inbound Rules

 - AWS>DEVSQL>Security Group>Inbound Rules

 - Terminal>DEVFILES/etc/exports file

My command:

 ->ssh -i PROD1.pem ubuntu@54.227.100.240
 ->sudo forever stopall
 ->sudo bash
 ->cd /opt/NYUAMS/node/ebs
 ->node app.js nfs

**Comment by leobardoramon** [comment]
I've figured it out!

I have to do a few things:

DEVFILES

 ->sudo bash
 ->mount /dev/xvdf /amsfiles
 ->sudo service nfs-kernel-server restart

DEVEBS

->sudo bash
->umount /amsfiles
 ->mount 10.0.2.51:/amsfiles /amsfiles

**Comment by leobardoramon** [comment]
Issue Resolved.

Closing.

**Comment by gosha1128** [comment]
Yes, now you see.  Its two kinds of "mount".

The first is to mount a data, block-device "VOLUME" to a machine, which
becomes part of the machines file system at /amsfiles.

The second is to mount an exported file system from one machine to another,
both at the location /amsfiles.

( The "mount" you are doing at a Mac machine is similar #2 above ).

-g
