### ISSUE TITLE
Test Case:  Admin/accounts/"New Account Wiz" - panel 3, university status

### ISSUE THREAD

**Issue by leobardoramon** [gosha1128/NYUAMS#594]
"Administrator" should be added to the university status dropdown

See screenshot

<img width="775" alt="screen shot 2016-08-20 at 5 18 00 pm" src="https://cloud.githubusercontent.com/assets/2165796/17833936/9252a4b4-66fa-11e6-8333-a2082568a3d8.png">

**Comment by gosha1128** [comment]
ok, you can test this now on dev...added administrator status

**Comment by leobardoramon** [comment]
verified
