### ISSUE TITLE
Test Case:  Admin/account/"New Account Wiz" - panel 4, cannot create account

### ISSUE THREAD

**Issue by leobardoramon** [gosha1128/NYUAMS#595]
Wizard does not complete account creation.  Even when all fields are populated, "not done yet" popup still appears, and account is not created.

**Comment by gosha1128** [comment]
That message means 'the developer of this feature is not done yet' :)

**Comment by leobardoramon** [comment]
oh, lol

**Comment by gosha1128** [comment]
ok, you can test this now...it will now attempt to create the account

**Comment by leobardoramon** [comment]
verified
