### ISSUE TITLE
End of AY Metrics Report

### ISSUE THREAD

**Issue by sjsmith24** [gosha1128/NYUAMS#615]
NYU IT Leadership has requested a full metrics report for the 2015/2016 academic year. Need a.s.a.p.

**Comment by gosha1128** [comment]
Leo - Since the current production instance does not have all our optimizations for metrics - I think the best thing to do is bring up temporarily an EC2 instance with a lot of memory and run a report.  Then turn off the instance.

**Comment by leobardoramon** [comment]
m3.xlarge seemed like it still wasn't powerful enough.  We'll try an m4.2xlarge next time.

Studio Activity:

[metrics_2016__8__4__21__4_44__274__112 AKA studio_activity.pdf](https://github.com/gosha1128/NYUAMS/files/451424/metrics_2016__8__4__21__4_44__274__112.AKA.studio_activity.pdf)

Account Grants Activity:

[metrics_2016__8__5__5__44_44__391__113 AKA account_grants_activity.pdf](https://github.com/gosha1128/NYUAMS/files/451426/metrics_2016__8__5__5__44_44__391__113.AKA.account_grants_activity.pdf)

Department Activity:

[metrics_2016__8__5__6__41_34__86__114 AKA department_activity.pdf](https://github.com/gosha1128/NYUAMS/files/451425/metrics_2016__8__5__6__41_34__86__114.AKA.department_activity.pdf)

University Activity:

[metrics_2016__8__5__7__36_47__529__115 AKA university_activity.pdf](https://github.com/gosha1128/NYUAMS/files/451427/metrics_2016__8__5__7__36_47__529__115.AKA.university_activity.pdf)

**Comment by gosha1128** [comment]
Leo - how long did it take for all the reports for an M3 instance ?

**Comment by leobardoramon** [comment]
It took 1 - 1.5 hours for each report. To ensure the completion of each report, I had to first wait for each subtab to finish loading,  then I had to "Generate" a PDF using the "Export PDF" panel.

Also important to carry over to #maintenance1 :
"
 ( although I did have to address the too-many-connections issue with a hotfix - please make sure to put that in github so that it carries over to maintenance1 ) 
/"

**Comment by gosha1128** [comment]
OK, i carried over the "hot-fix" to maintenance1.

**Comment by leobardoramon** [comment]
Thank you
