### ISSUE TITLE
AWS Security

### ISSUE THREAD

**Issue by leobardoramon** [gosha1128/NYUAMS#616]
AWS has expressed concern with our level of security.  See Below:

"Another thing that I want bring to your attention: While I was looking at instance, i-8a854415, I noticed that the security group is allowing access on all ports for any protocol from the World 0.0.0.0/0, as well as specifically allowing access to port 22. Having ports open to the world like this, can leave you vulnerable to attack by unscrupulous individuals. To minimize risk and improve security to your instance, I'd like to suggest that you update your security group, firstly by removing the rule allowing all access to any port from 0.0.0.0/0; as well as changing the port 22 rule to only allow access from a specific IP range that require access to the instance. 

I hope this gives you some guidance on how to migrate your data from EFS to EFS. Please let us know if you need more information.

Best regards,

Stefan F.
Amazon Web Services
/"

What should we do?

**Comment by gosha1128** [comment]
Sounds right.  Just remove the 0.0.0.0 rule...but keep 22.  The way we've
configured access is that you need the PEM key...

**Comment by leobardoramon** [comment]
Done.

Don't forget to add Inbound (a) Custom UDP and (b) Custom TCP rules for the corresponding VPC CIDR ( x.x.x.x/16 ) for each respective security group for (1) Database ( _EBS ) , (2) Fileserver ( _FILES ) , (3) SQL server ( _sql )

Closing
