### ISSUE TITLE
Trouble starting the QAEBS ( 52.200.89.172 ) server

### ISSUE THREAD

**Issue by leobardoramon** [gosha1128/NYUAMS#640]
when I run the command
>>node app.js nfs
nothing happens, it just gives me a new prompt line

<img width="589" alt="screen shot 2016-10-07 at 2 46 00 pm" src="https://cloud.githubusercontent.com/assets/2165796/19201688/d2f99460-8c9c-11e6-9b2b-b71eab7d59fe.png">
<img width="586" alt="screen shot 2016-10-07 at 2 46 10 pm" src="https://cloud.githubusercontent.com/assets/2165796/19201687/d2f90acc-8c9c-11e6-93c7-ec37c9457563.png">

I tried rebooting ubuntu, this didn't help.

any suggestions?

**Comment by leobardoramon** [comment]
I got it...fileserver was not mounted...

ty.

Closing

**Comment by gosha1128** [comment]
Yes also the debugging was not verbose...I should show you how to change
it...
